// Auto-generated by schema-salad-plus-pydantic — do not edit.

import { Schema } from "effect";

/**
 * Salad data types are based on Avro schema declarations.  Refer to the
[Avro schema declaration documentation](https://avro.apache.org/docs/current/spec.html#schemas) for
detailed information.

null: no value
boolean: a binary value
int: 32-bit signed integer
long: 64-bit signed integer
float: single precision (32-bit) IEEE 754 floating-point number
double: double precision (64-bit) IEEE 754 floating-point number
string: Unicode character sequence
 */
export const PrimitiveTypeSchema = Schema.Literal(
  "null",
  "boolean",
  "int",
  "long",
  "float",
  "double",
  "string",
);
export type PrimitiveType = typeof PrimitiveTypeSchema.Type;

/**
 * Extends primitive types with the native Galaxy concepts such datasets and collections.
integer: an alias for int type - matches syntax used by Galaxy tools
text: an alias for string type - matches syntax used by Galaxy tools
File: an alias for data - there are subtle differences between a plain file, the CWL concept of 'File', and the Galaxy concept of a dataset - this may have subtly difference semantics in the future
data: a Galaxy dataset
collection: a Galaxy dataset collection
 */
export const GalaxyTypeSchema = Schema.Literal(
  "null",
  "boolean",
  "int",
  "long",
  "float",
  "double",
  "string",
  "integer",
  "text",
  "File",
  "data",
  "collection",
);
export type GalaxyType = typeof GalaxyTypeSchema.Type;

/**
 * Module types used by Galaxy steps. Galaxy's native format allows additional types such as data_input, data_input_collection, and parameter_type
but these should be represented as ``inputs`` in Format2.

tool: Run a tool.
subworkflow: Run a subworkflow.
pause: Pause computation on this branch of workflow until user allows it to continue.
pick_value: Select the first non-null value from multiple inputs. Used to merge branches of conditional or optional workflow paths.
 */
export const WorkflowStepTypeSchema = Schema.Literal("tool", "subworkflow", "pause", "pick_value");
export type WorkflowStepType = typeof WorkflowStepTypeSchema.Type;

export const DocumentedSchema = Schema.Struct({
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc: Schema.optional(Schema.Union(Schema.Null, Schema.String, Schema.Array(Schema.String))),
});
export type Documented = typeof DocumentedSchema.Type;

/**
 * Define an enumerated type.
 */
export const EnumSchemaSchema = Schema.Struct({
  /** Defines the set of valid symbols. */
  symbols: Schema.Array(Schema.String),
  /** Must be `enum` */
  type: Schema.Literal("enum"),
});
export type EnumSchema = typeof EnumSchemaSchema.Type;

export const RecordSchemaSchema = Schema.Struct({
  /** Defines the fields of the record. */
  fields: Schema.optional(
    Schema.Union(
      Schema.Null,
      Schema.Array(Schema.suspend((): Schema.Schema<any> => RecordFieldSchema)),
    ),
  ),
  /** Must be `record` */
  type: Schema.Literal("record"),
});
export type RecordSchema = typeof RecordSchemaSchema.Type;

export const ArraySchemaSchema = Schema.Struct({
  /** Defines the type of the array elements. */
  items: Schema.Union(
    PrimitiveTypeSchema,
    RecordSchemaSchema,
    EnumSchemaSchema,
    Schema.suspend((): Schema.Schema<any> => ArraySchemaSchema),
    Schema.String,
    Schema.Array(
      Schema.Union(
        PrimitiveTypeSchema,
        RecordSchemaSchema,
        EnumSchemaSchema,
        Schema.suspend((): Schema.Schema<any> => ArraySchemaSchema),
        Schema.String,
      ),
    ),
  ),
  /** Must be `array` */
  type: Schema.Literal("array"),
});
export type ArraySchema = typeof ArraySchemaSchema.Type;

/**
 * A field of a record.
 */
export const RecordFieldSchema = Schema.Struct({
  ...DocumentedSchema.fields,
  /** The name of the field */
  name: Schema.String,
  /** The field type */
  type: Schema.Union(
    PrimitiveTypeSchema,
    RecordSchemaSchema,
    EnumSchemaSchema,
    ArraySchemaSchema,
    Schema.String,
    Schema.Array(
      Schema.Union(
        PrimitiveTypeSchema,
        RecordSchemaSchema,
        EnumSchemaSchema,
        ArraySchemaSchema,
        Schema.String,
      ),
    ),
  ),
});
export type RecordField = typeof RecordFieldSchema.Type;

export const LabeledSchema = Schema.Struct({
  /** A short, human-readable label of this object. */
  label: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type Labeled = typeof LabeledSchema.Type;

export const IdentifiedSchema = Schema.Struct({
  /** The unique identifier for this object. */
  id: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type Identified = typeof IdentifiedSchema.Type;

/**
 * Define an input or output parameter to a process.
 */
export const ParameterSchema = Schema.Struct({
  ...LabeledSchema.fields,
  ...DocumentedSchema.fields,
  ...IdentifiedSchema.fields,
});
export type Parameter = typeof ParameterSchema.Type;

export const InputParameterSchema = Schema.Struct({
  ...ParameterSchema.fields,
  /** The unique identifier for this object. */
  id: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** A short, human-readable label of this object. */
  label: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc: Schema.optional(Schema.Union(Schema.Null, Schema.String, Schema.Array(Schema.String))),
  /** The default value to use for this parameter if the parameter is missing from the input object, or if the value of the parameter in the input object is `null`.  Default values are applied before eva... */
  default: Schema.optional(Schema.Union(Schema.Null, Schema.Unknown)),
});
export type InputParameter = typeof InputParameterSchema.Type;

export const OutputParameterSchema = Schema.Struct({
  ...ParameterSchema.fields,
  /** The unique identifier for this object. */
  id: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** A short, human-readable label of this object. */
  label: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc: Schema.optional(Schema.Union(Schema.Null, Schema.String, Schema.Array(Schema.String))),
});
export type OutputParameter = typeof OutputParameterSchema.Type;

/**
 * Describe an output parameter of a workflow.  The parameter must be
connected to one parameter defined in the workflow that
will provide the value of the output parameter. It is legal to
connect a WorkflowInputParameter to a WorkflowOutputParameter.
 */
export const WorkflowOutputParameterSchema = Schema.Struct({
  ...OutputParameterSchema.fields,
  /** The unique identifier for this object. */
  id: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** A short, human-readable label of this object. */
  label: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc: Schema.optional(Schema.Union(Schema.Null, Schema.String, Schema.Array(Schema.String))),
  /** Specifies workflow parameter that supply the value of to the output parameter. */
  outputSource: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Specify valid types of data that may be assigned to this parameter. */
  type: Schema.optional(Schema.Union(Schema.Null, GalaxyTypeSchema)),
});
export type WorkflowOutputParameter = typeof WorkflowOutputParameterSchema.Type;

/**
 * This field specifies the location of the step's node when rendered in the workflow editor.
 */
export const StepPositionSchema = Schema.Struct({
  /** Relative vertical position of the step's node when rendered in the workflow editor. */
  top: Schema.Number,
  /** Relative horizontal position of the step's node when rendered in the workflow editor. */
  left: Schema.Number,
});
export type StepPosition = typeof StepPositionSchema.Type;

export const HasStepPositionSchema = Schema.Struct({
  position: Schema.optional(Schema.Union(Schema.Null, StepPositionSchema)),
});
export type HasStepPosition = typeof HasStepPositionSchema.Type;

export const WorkflowInputParameterSchema = Schema.Struct({
  ...InputParameterSchema.fields,
  ...HasStepPositionSchema.fields,
  /** The unique identifier for this object. */
  id: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** A short, human-readable label of this object. */
  label: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc: Schema.optional(Schema.Union(Schema.Null, Schema.String, Schema.Array(Schema.String))),
  /** Specify valid types of data that may be assigned to this parameter. */
  type: Schema.optional(
    Schema.Union(GalaxyTypeSchema, Schema.Null, Schema.Array(GalaxyTypeSchema)),
  ),
  /** If set to true, `WorkflowInputParameter` is not required to submit the workflow. */
  optional: Schema.optional(Schema.Union(Schema.Boolean, Schema.Null)),
  /** Specify datatype extension for valid input datasets. */
  format: Schema.optional(Schema.Union(Schema.Null, Schema.Array(Schema.String))),
  /** Collection type (defaults to `list` if `type` is `collection`). Nested collection types are separated with colons, e.g. `list:list:paired`. */
  collection_type: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type WorkflowInputParameter = typeof WorkflowInputParameterSchema.Type;

/**
 * The base executable type in CWL is the `Process` object defined by the
document.  Note that the `Process` object is abstract and cannot be
directly executed.
 */
export const ProcessSchema = Schema.Struct({
  ...IdentifiedSchema.fields,
  ...LabeledSchema.fields,
  ...DocumentedSchema.fields,
  /** Defines the input parameters of the process.  The process is ready to run when all required input parameters are associated with concrete values.  Input parameters include a schema for each paramet... */
  inputs: Schema.Union(
    Schema.Array(WorkflowInputParameterSchema),
    Schema.Record({
      key: Schema.String,
      value: Schema.Union(WorkflowInputParameterSchema, Schema.String),
    }),
    Schema.Record({ key: Schema.String, value: Schema.Unknown }),
  ),
  /** Defines the parameters representing the output of the process.  May be used to generate and/or validate the output object. */
  outputs: Schema.Union(
    Schema.Array(WorkflowOutputParameterSchema),
    Schema.Record({
      key: Schema.String,
      value: Schema.Union(WorkflowOutputParameterSchema, Schema.String),
    }),
    Schema.Record({ key: Schema.String, value: Schema.Unknown }),
  ),
});
export type Process = typeof ProcessSchema.Type;

export const HasUUIDSchema = Schema.Struct({
  /** UUID uniquely representing this element. */
  uuid: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type HasUUID = typeof HasUUIDSchema.Type;

export const HasStepErrorsSchema = Schema.Struct({
  /** During Galaxy export there may be some problem validating the tool state, tool used, etc.. that will be indicated by this field. The Galaxy user should be warned of these problems before the workfl... */
  errors: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type HasStepErrors = typeof HasStepErrorsSchema.Type;

export const ToolShedRepositorySchema = Schema.Struct({
  /** The name of the tool shed repository this tool can be found in. */
  name: Schema.String,
  /** The revision of the tool shed repository this tool can be found in. */
  changeset_revision: Schema.String,
  /** The owner of the tool shed repository this tool can be found in. */
  owner: Schema.String,
  /** The URI of the tool shed containing the repository this tool can be found in - typically this should be toolshed.g2.bx.psu.edu. */
  tool_shed: Schema.String,
});
export type ToolShedRepository = typeof ToolShedRepositorySchema.Type;

export const ReferencesToolSchema = Schema.Struct({
  /** The tool ID used to run this step of the workflow (e.g. 'cat1' or 'toolshed.g2.bx.psu.edu/repos/nml/collapse_collections/collapse_dataset/4.0'). */
  tool_id: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** The Galaxy Tool Shed repository that should be installed in order to use this tool. */
  tool_shed_repository: Schema.optional(Schema.Union(Schema.Null, ToolShedRepositorySchema)),
  /** The tool version corresponding used to run this step of the workflow. For tool shed installed tools, the ID generally uniquely specifies a version and this field is optional. */
  tool_version: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type ReferencesTool = typeof ReferencesToolSchema.Type;

/**
 * Associate an output parameter of the underlying process with a workflow
parameter.  The workflow parameter (given in the `id` field) be may be used
as a `source` to connect with input parameters of other workflow steps, or
with an output parameter of the process.

A unique identifier for this workflow output parameter.  This is
the identifier to use in the `source` field of `WorkflowStepInput`
to connect the output value to downstream parameters.
 */
export const WorkflowStepOutputSchema = Schema.Struct({
  ...IdentifiedSchema.fields,
  add_tags: Schema.optional(Schema.Union(Schema.Null, Schema.Array(Schema.String))),
  change_datatype: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  delete_intermediate_datasets: Schema.optional(Schema.Union(Schema.Null, Schema.Boolean)),
  hide: Schema.optional(Schema.Union(Schema.Null, Schema.Boolean)),
  remove_tags: Schema.optional(Schema.Union(Schema.Null, Schema.Array(Schema.String))),
  rename: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  set_columns: Schema.optional(
    Schema.Union(Schema.Record({ key: Schema.String, value: Schema.Unknown }), Schema.Null),
  ),
});
export type WorkflowStepOutput = typeof WorkflowStepOutputSchema.Type;

export const SinkSchema = Schema.Struct({
  /** Specifies one or more workflow parameters that will provide input to the underlying step parameter. */
  source: Schema.optional(Schema.Union(Schema.Null, Schema.String, Schema.Array(Schema.String))),
});
export type Sink = typeof SinkSchema.Type;

/**
 * TODO:
 */
export const WorkflowStepInputSchema = Schema.Struct({
  ...IdentifiedSchema.fields,
  ...SinkSchema.fields,
  ...LabeledSchema.fields,
  /** The default value for this parameter to use if either there is no `source` field, or the value produced by the `source` is `null`.  The default must be applied prior to scattering or evaluating `va... */
  default: Schema.optional(Schema.Union(Schema.Null, Schema.Unknown)),
});
export type WorkflowStepInput = typeof WorkflowStepInputSchema.Type;

/**
 * Definition of an invocation report for this workflow. Currently the only
field is 'markdown'.
 */
export const ReportSchema = Schema.Struct({
  /** Galaxy flavored Markdown to define an invocation report. */
  markdown: Schema.String,
});
export type Report = typeof ReportSchema.Type;

/**
 * Base fields shared by all comment types.
 */
export const BaseCommentSchema = Schema.Struct({
  /** Position of the comment on the editor canvas as ``[x, y]`` coordinates. */
  position: Schema.optional(Schema.Union(Schema.Array(Schema.Number), Schema.Null)),
  /** Size of the comment as ``[width, height]``. */
  size: Schema.optional(Schema.Union(Schema.Array(Schema.Number), Schema.Null)),
  /** Display color of the comment (e.g. ``"none"``, ``"blue"``). */
  color: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Optional label for referencing this comment from frame ``contains_comments`` fields or for use as a map key when comments are represented as a mapping. */
  label: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type BaseComment = typeof BaseCommentSchema.Type;

/**
 * A plain text annotation in the workflow editor.
 */
export const TextCommentSchema = Schema.Struct({
  ...BaseCommentSchema.fields,
  /** Comment type (``text``). */
  type: Schema.Literal("text"),
  /** The text content. */
  text: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Whether the text is displayed in bold. */
  bold: Schema.optional(Schema.Union(Schema.Null, Schema.Boolean)),
  /** Whether the text is displayed in italic. */
  italic: Schema.optional(Schema.Union(Schema.Null, Schema.Boolean)),
  /** Font size of the text. */
  text_size: Schema.optional(Schema.Union(Schema.Null, Schema.Number)),
});
export type TextComment = typeof TextCommentSchema.Type;

/**
 * A Markdown-rendered annotation in the workflow editor.
 */
export const MarkdownCommentSchema = Schema.Struct({
  ...BaseCommentSchema.fields,
  /** Comment type (``markdown``). */
  type: Schema.Literal("markdown"),
  /** Markdown content. */
  text: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type MarkdownComment = typeof MarkdownCommentSchema.Type;

/**
 * A freehand drawn line on the editor canvas.
 */
export const FreehandCommentSchema = Schema.Struct({
  ...BaseCommentSchema.fields,
  /** Comment type (``freehand``). */
  type: Schema.Literal("freehand"),
  /** Line thickness. */
  thickness: Schema.optional(Schema.Union(Schema.Null, Schema.Number)),
  /** Array of ``[x, y]`` coordinate pairs defining the freehand line path. */
  line: Schema.optional(Schema.Union(Schema.Array(Schema.Array(Schema.Number)), Schema.Null)),
});
export type FreehandComment = typeof FreehandCommentSchema.Type;

/**
 * Base fields shared by all creator types, corresponding to schema.org
Thing properties common to both Person and Organization.
 */
export const BaseCreatorSchema = Schema.Struct({
  /** Full name of the person or organization. */
  name: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Persistent identifier, typically an ORCID URL (e.g. ``https://orcid.org/0000-0001-2345-6789``) or bare ORCID. */
  identifier: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Website or profile URL. */
  url: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Email address. May include a ``mailto:`` prefix. */
  email: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** URL to an image or avatar. */
  image: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Physical or mailing address. */
  address: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** An alternate name or alias. */
  alternateName: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Telephone number. */
  telephone: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Fax number. */
  faxNumber: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type BaseCreator = typeof BaseCreatorSchema.Type;

/**
 * A person who created or contributed to the workflow.
Corresponds to a `schema.org Person <https://schema.org/Person>`_.
 */
export const CreatorPersonSchema = Schema.Struct({
  ...BaseCreatorSchema.fields,
  /** Creator type discriminator (``Person``). */
  class: Schema.Literal("Person"),
  /** Given (first) name. */
  givenName: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Family (last) name. */
  familyName: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Honorific prefix (e.g. ``Dr``, ``Prof``). */
  honorificPrefix: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Honorific suffix (e.g. ``M.D.``, ``PhD``). */
  honorificSuffix: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Job title or role. */
  jobTitle: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type CreatorPerson = typeof CreatorPersonSchema.Type;

/**
 * A rectangular grouping box that visually contains steps and other comments.
 */
export const FrameCommentSchema = Schema.Struct({
  ...BaseCommentSchema.fields,
  /** Comment type (``frame``). */
  type: Schema.Literal("frame"),
  /** Title displayed on the frame header. */
  title: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Step labels or indices contained within this frame. */
  contains_steps: Schema.optional(
    Schema.Union(Schema.Null, Schema.Array(Schema.Union(Schema.String, Schema.Number))),
  ),
  /** Comment labels or indices contained within this frame. */
  contains_comments: Schema.optional(
    Schema.Union(Schema.Null, Schema.Array(Schema.Union(Schema.String, Schema.Number))),
  ),
});
export type FrameComment = typeof FrameCommentSchema.Type;

/**
 * An organization that created or contributed to the workflow.
Corresponds to a `schema.org Organization <https://schema.org/Organization>`_.
 */
export const CreatorOrganizationSchema = Schema.Struct({
  ...BaseCreatorSchema.fields,
  /** Creator type discriminator (``Organization``). */
  class: Schema.Literal("Organization"),
});
export type CreatorOrganization = typeof CreatorOrganizationSchema.Type;

/**
 * A Galaxy workflow description. This record corresponds to the description of a workflow that should be executable
on a Galaxy server that includes the contained tool definitions.

The workflows API or the user interface of Galaxy instances that are of version 19.09 or newer should be able to
import a document defining this record.

## A note about `label` field.

This is the name of the workflow in the Galaxy user interface. This is the mechanism that
users will primarily identify the workflow using. Legacy support - this may also be called 'name' and Galaxy will
consume the workflow document fine and treat this attribute correctly - however in order to validate against this
workflow definition schema the attribute should be called `label`.
 */
export const GalaxyWorkflowSchema = Schema.Struct({
  ...ProcessSchema.fields,
  ...HasUUIDSchema.fields,
  /** The unique identifier for this object. */
  id: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  class: Schema.Literal("GalaxyWorkflow"),
  /** A short, human-readable label of this object. */
  label: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc: Schema.optional(Schema.Union(Schema.Null, Schema.String, Schema.Array(Schema.String))),
  /** The individual steps that make up the workflow. Each step is executed when all of its input data links are fulfilled. */
  steps: Schema.Union(
    Schema.Array(Schema.suspend((): Schema.Schema<any> => WorkflowStepSchema)),
    Schema.Record({
      key: Schema.String,
      value: Schema.suspend((): Schema.Schema<any> => WorkflowStepSchema),
    }),
  ),
  /** Workflow invocation report template. */
  report: Schema.optional(Schema.Union(Schema.Null, ReportSchema)),
  /** Tags for the workflow. */
  tags: Schema.optional(Schema.Union(Schema.Array(Schema.String), Schema.Null)),
  /** Visual annotations for the workflow editor canvas. Comments are non-functional and do not affect workflow execution. May be specified as a list or as a mapping keyed by label. */
  comments: Schema.optional(
    Schema.Union(
      Schema.Array(
        Schema.Union(
          TextCommentSchema,
          MarkdownCommentSchema,
          FrameCommentSchema,
          FreehandCommentSchema,
        ),
      ),
      Schema.Record({
        key: Schema.String,
        value: Schema.Union(
          TextCommentSchema,
          MarkdownCommentSchema,
          FrameCommentSchema,
          FreehandCommentSchema,
        ),
      }),
      Schema.Null,
    ),
  ),
  /** Workflow creators. Can be schema.org Person (https://schema.org/Person) or Organization (https://schema.org/Organization) entities. */
  creator: Schema.optional(
    Schema.Union(
      Schema.Array(Schema.Union(CreatorPersonSchema, CreatorOrganizationSchema)),
      Schema.Null,
    ),
  ),
  /** Must be a valid license listed at https://spdx.org/licenses/ */
  license: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** If listed should correspond to the release of the workflow in its source reposiory. */
  release: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type GalaxyWorkflow = typeof GalaxyWorkflowSchema.Type;

/**
 * This represents a non-input step a Galaxy Workflow.

# A note about `state` and `tool_state` fields.

Only one or the other should be specified. These are two ways to represent the "state"
of a tool at this workflow step. Both are essentially maps from parameter names to
parameter values.

`tool_state` is much more low-level and expects a flat dictionary with each value a JSON
dump. Nested tool structures such as conditionals and repeats should have all their values
in the JSON dumped string. In general `tool_state` may be present in workflows exported from
Galaxy but shouldn't be written by humans.

`state` can contained a typed map. Repeat values can be represented as YAML arrays. An alternative
to representing `state` this way is defining inputs with default values.
 */
export const WorkflowStepSchema = Schema.Struct({
  ...IdentifiedSchema.fields,
  ...LabeledSchema.fields,
  ...DocumentedSchema.fields,
  ...HasStepPositionSchema.fields,
  ...ReferencesToolSchema.fields,
  ...HasStepErrorsSchema.fields,
  ...HasUUIDSchema.fields,
  /** Defines the input parameters of the workflow step.  The process is ready to run when all required input parameters are associated with concrete values.  Input parameters include a schema for each p... */
  in: Schema.optional(
    Schema.Union(
      Schema.Array(WorkflowStepInputSchema),
      Schema.Record({
        key: Schema.String,
        value: Schema.Union(WorkflowStepInputSchema, Schema.String),
      }),
      Schema.Null,
    ),
  ),
  /** Defines the parameters representing the output of the process.  May be used to generate and/or validate the output object.  This can also be called 'outputs' for legacy reasons - but the resulting ... */
  out: Schema.optional(
    Schema.Union(
      Schema.Array(Schema.Union(WorkflowStepOutputSchema, Schema.String)),
      Schema.Record({
        key: Schema.String,
        value: Schema.Union(WorkflowStepOutputSchema, Schema.String),
      }),
      Schema.Null,
    ),
  ),
  /** Structured tool state. */
  state: Schema.optional(
    Schema.Union(Schema.Record({ key: Schema.String, value: Schema.Unknown }), Schema.Null),
  ),
  /** Unstructured tool state. */
  tool_state: Schema.optional(
    Schema.Union(
      Schema.String,
      Schema.Record({ key: Schema.String, value: Schema.Unknown }),
      Schema.Null,
    ),
  ),
  /** Workflow step module's type (defaults to 'tool'). */
  type: Schema.optional(Schema.Union(Schema.Null, WorkflowStepTypeSchema)),
  /** Specifies a subworkflow to run. May be an inline workflow definition, a URL string, or an @import reference dict. */
  run: Schema.optional(
    Schema.Union(
      GalaxyWorkflowSchema,
      Schema.String,
      Schema.Record({ key: Schema.String, value: Schema.Unknown }),
      Schema.Null,
    ),
  ),
  runtime_inputs: Schema.optional(Schema.Union(Schema.Null, Schema.Array(Schema.String))),
  /** If defined, only run the step when the expression evaluates to `true`.  If `false` the step is skipped.  A skipped step produces a `null` on each output.  Expression should be an ecma5.1 expression. */
  when: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type WorkflowStep = typeof WorkflowStepSchema.Type;
