// Auto-generated by schema-salad-plus-pydantic — do not edit.

/**
 * Salad data types are based on Avro schema declarations.  Refer to the
[Avro schema declaration documentation](https://avro.apache.org/docs/current/spec.html#schemas) for
detailed information.

null: no value
boolean: a binary value
int: 32-bit signed integer
long: 64-bit signed integer
float: single precision (32-bit) IEEE 754 floating-point number
double: double precision (64-bit) IEEE 754 floating-point number
string: Unicode character sequence
 */
export type PrimitiveType = "null" | "boolean" | "int" | "long" | "float" | "double" | "string";

/**
 * Extends primitive types with the native Galaxy concepts such as datasets and collections.
Normalized gxformat2 workflow input declaration spellings are ``data``, ``collection``, ``string``, ``int``, ``float``, and ``boolean``. Other spellings are accepted as compatibility aliases on import but normalized gxformat2 output emits the normalized spellings.
data: one Galaxy dataset input. Native Galaxy ``data_input`` converts to this spelling.
File: accepted alias for ``data``, but normalized gxformat2 output emits ``data``. Note: workflow **test job** YAML uses ``type: File`` to mean 'stage this file as test input data', which is a separate concept from workflow input declaration.
collection: one Galaxy dataset collection input. Native Galaxy ``data_collection_input`` converts to this spelling.
string: normalized gxformat2 spelling for native Galaxy text workflow parameters.
text: accepted alias for ``string`` because native Galaxy parameter state and Galaxy tool XML terminology use ``text``.
int: normalized gxformat2 spelling for native Galaxy integer workflow parameters.
integer: accepted alias for ``int`` because native Galaxy parameter state and Galaxy tool XML terminology use ``integer``.
 */
export type GalaxyType =
  | "null"
  | "boolean"
  | "int"
  | "long"
  | "float"
  | "double"
  | "string"
  | "integer"
  | "text"
  | "File"
  | "data"
  | "collection";

/**
 * Module types used by Galaxy steps. Galaxy's native format allows additional types such as data_input, data_input_collection, and parameter_type
but these should be represented as ``inputs`` in Format2.

tool: Run a tool.
subworkflow: Run a subworkflow.
pause: Pause computation on this branch of workflow until user allows it to continue.
pick_value: Select the first non-null value from multiple inputs. Used to merge branches of conditional or optional workflow paths.
 */
export type WorkflowStepType = "tool" | "subworkflow" | "pause" | "pick_value";

export interface Documented {
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc?: null | string | Array<string>;
}

/**
 * A field of a record.
 */
export interface RecordField extends Documented {
  /** The name of the field */
  name: string;
  /** The field type */
  type:
    | PrimitiveType
    | RecordSchema
    | EnumSchema
    | ArraySchema
    | string
    | Array<PrimitiveType | RecordSchema | EnumSchema | ArraySchema | string>;
}

export interface RecordSchema {
  /** Defines the fields of the record. */
  fields?: null | Array<RecordField>;
  /** Must be `record` */
  type: "record";
}

/**
 * Define an enumerated type.
 */
export interface EnumSchema {
  /** Defines the set of valid symbols. */
  symbols: Array<string>;
  /** Must be `enum` */
  type: "enum";
}

export interface ArraySchema {
  /** Defines the type of the array elements. */
  items:
    | PrimitiveType
    | RecordSchema
    | EnumSchema
    | ArraySchema
    | string
    | Array<PrimitiveType | RecordSchema | EnumSchema | ArraySchema | string>;
  /** Must be `array` */
  type: "array";
}

export interface Labeled {
  /** A short, human-readable label of this object. */
  label?: null | string;
}

export interface Identified {
  /** The unique identifier for this object. */
  id?: null | string;
}

/**
 * Define an input or output parameter to a process.
 */
export interface Parameter extends Labeled, Documented, Identified {}

export interface InputParameter extends Parameter {
  /** The unique identifier for this object. */
  id?: null | string;
  /** A short, human-readable label of this object. */
  label?: null | string;
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc?: null | string | Array<string>;
  /** The default value to use for this parameter if the parameter is missing from the input object, or if the value of the parameter in the input object is `null`.  Default values are applied before eva... */
  default?: null | unknown;
}

export interface OutputParameter extends Parameter {
  /** The unique identifier for this object. */
  id?: null | string;
  /** A short, human-readable label of this object. */
  label?: null | string;
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc?: null | string | Array<string>;
}

/**
 * The base executable type in CWL is the `Process` object defined by the
document.  Note that the `Process` object is abstract and cannot be
directly executed.
 */
export interface Process extends Identified, Labeled, Documented {
  /** Defines the input parameters of the process.  The process is ready to run when all required input parameters are associated with concrete values.  Input parameters include a schema for each paramet... */
  inputs:
    | Array<
        | WorkflowDataParameter
        | WorkflowCollectionParameter
        | WorkflowIntegerParameter
        | WorkflowFloatParameter
        | WorkflowTextParameter
        | WorkflowBooleanParameter
      >
    | Record<
        string,
        | WorkflowDataParameter
        | WorkflowCollectionParameter
        | WorkflowIntegerParameter
        | WorkflowFloatParameter
        | WorkflowTextParameter
        | WorkflowBooleanParameter
        | string
      >
    | Record<string, unknown>;
  /** Defines the parameters representing the output of the process.  May be used to generate and/or validate the output object. */
  outputs:
    | Array<WorkflowOutputParameter>
    | Record<string, WorkflowOutputParameter | string>
    | Record<string, unknown>;
}

export interface HasUUID {
  /** UUID uniquely representing this element. */
  uuid?: null | string;
}

export interface HasStepErrors {
  /** During Galaxy export there may be some problem validating the tool state, tool used, etc.. that will be indicated by this field. The Galaxy user should be warned of these problems before the workfl... */
  errors?: null | string;
}

export interface HasStepPosition {
  position?: null | StepPosition;
}

/**
 * This field specifies the location of the step's node when rendered in the workflow editor.
 */
export interface StepPosition {
  /** Relative vertical position of the step's node when rendered in the workflow editor. */
  top: number;
  /** Relative horizontal position of the step's node when rendered in the workflow editor. */
  left: number;
}

export interface ReferencesTool {
  /** The tool ID used to run this step of the workflow (e.g. 'cat1' or 'toolshed.g2.bx.psu.edu/repos/nml/collapse_collections/collapse_dataset/4.0'). */
  tool_id?: null | string;
  /** The Galaxy Tool Shed repository that should be installed in order to use this tool. */
  tool_shed_repository?: null | ToolShedRepository;
  /** The tool version corresponding used to run this step of the workflow. For tool shed installed tools, the ID generally uniquely specifies a version and this field is optional. */
  tool_version?: null | string;
}

/**
 * Describes one column of a sample-sheet collection input.
Used in `column_definitions` on a `collection_type: sample_sheet[:<type>]`
workflow input.
 */
export interface SampleSheetColumnDefinition {
  /** Column name. Must not contain special characters (matches `^[\w\-_ \?]*$`). */
  name: string;
  /** Optional human-readable column description. */
  description?: null | string;
  /** Value type for this column. One of `string`, `int`, `float`, `boolean`, or `element_identifier`. Mirrors Galaxy's runtime `SampleSheetColumnType`. */
  type: "string" | "int" | "float" | "boolean" | "element_identifier";
  /** If true, rows may omit a value for this column. */
  optional: boolean;
  /** Default value used when a row omits this column. Type must be compatible with `type` - validated by the pydantic post-validator. */
  default_value?: null | string | number | boolean;
  /** Galaxy-style parameter validators. Modelled as opaque records here - full validator schema lives in galaxy.tool_util_models. */
  validators?: null | Array<unknown>;
  /** Closed set of permitted values for this column. Item type must be compatible with the column `type` (post-validated). */
  restrictions?: null | Array<string | number | number | boolean>;
  /** Open suggestion list for this column. */
  suggestions?: null | Array<string | number | number | boolean>;
}

/**
 * Describes one field of a `record` collection input.
Used in `fields` on a `collection_type` containing `record` (e.g.
`record`, `list:record`, `sample_sheet:record`). Mirrors a subset of
the CWL `InputRecordSchema` shape that Galaxy persists on
`DatasetCollection.fields`.
 */
export interface RecordFieldDefinition {
  /** Field name. Must equal the corresponding element identifier in the materialized record collection. */
  name: string;
  /** Field value type. A subset of the CWL primitive types: `File`, `null`, `boolean`, `int`, `float`, `string`. May be a list to express a union (e.g. `["File", "null"]` for an optional file). */
  type:
    | "File"
    | "null"
    | "boolean"
    | "int"
    | "float"
    | "string"
    | Array<"File" | "null" | "boolean" | "int" | "float" | "string">;
  /** Optional Galaxy datatype hint for `File`-typed fields. */
  format?: null | string;
}

/**
 * A `{value, label}` option used in `restrictions` or `suggestions` on a
text workflow parameter. Plain strings are also accepted in those
arrays as shorthand for `{value: <str>, label: <str>}`.
 */
export interface WorkflowTextOption {
  /** Machine value submitted to the connected tool input. */
  value: string;
  /** Human label shown in Galaxy. Defaults to `value` when omitted. */
  label?: null | string;
}

export interface ToolShedRepository {
  /** The name of the tool shed repository this tool can be found in. */
  name: string;
  /** The revision of the tool shed repository this tool can be found in. */
  changeset_revision: string;
  /** The owner of the tool shed repository this tool can be found in. */
  owner: string;
  /** The URI of the tool shed containing the repository this tool can be found in - typically this should be toolshed.g2.bx.psu.edu. */
  tool_shed: string;
}

export interface BaseInputParameter extends InputParameter, HasStepPosition {
  /** The unique identifier for this object. */
  id?: null | string;
  /** A short, human-readable label of this object. */
  label?: null | string;
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc?: null | string | Array<string>;
  /** Controls whether Galaxy allows invocation of the workflow without a user-supplied value for this input. If ``true``, the input may be omitted at invocation time. ``optional`` and ``default`` are in... */
  optional?: boolean | null;
}

export interface BaseDataParameter extends BaseInputParameter {
  /** The unique identifier for this object. */
  id?: null | string;
  /** A short, human-readable label of this object. */
  label?: null | string;
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc?: null | string | Array<string>;
  /** The default value to use for this parameter if the parameter is missing from the input object, or if the value of the parameter in the input object is `null`.  Default values are applied before eva... */
  default?: null | unknown;
  position?: null | StepPosition;
  /** Specify datatype extensions for valid input datasets. */
  format?: null | Array<string>;
}

/**
 * A data input parameter for a Galaxy workflow. Represents one Galaxy dataset.
Normalized gxformat2 output uses ``type: data``. ``type: File`` is accepted as
an alias, but should not be confused with workflow test job syntax where
``type: File`` means stage a file as test input data.
 */
export interface WorkflowDataParameter extends BaseDataParameter {
  /** The unique identifier for this object. */
  id?: null | string;
  /** A short, human-readable label of this object. */
  label?: null | string;
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc?: null | string | Array<string>;
  /** The default value to use for this parameter if the parameter is missing from the input object, or if the value of the parameter in the input object is `null`.  Default values are applied before eva... */
  default?: null | unknown;
  position?: null | StepPosition;
  /** Controls whether Galaxy allows invocation of the workflow without a user-supplied value for this input. If ``true``, the input may be omitted at invocation time. ``optional`` and ``default`` are in... */
  optional?: boolean | null;
  /** Specify valid types of data that may be assigned to this parameter. */
  type?: "data" | "File" | null;
}

/**
 * A collection input parameter for a Galaxy workflow - represents a dataset collection.
 */
export interface WorkflowCollectionParameter extends BaseDataParameter {
  /** The unique identifier for this object. */
  id?: null | string;
  /** A short, human-readable label of this object. */
  label?: null | string;
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc?: null | string | Array<string>;
  /** The default value to use for this parameter if the parameter is missing from the input object, or if the value of the parameter in the input object is `null`.  Default values are applied before eva... */
  default?: null | unknown;
  position?: null | StepPosition;
  /** Controls whether Galaxy allows invocation of the workflow without a user-supplied value for this input. If ``true``, the input may be omitted at invocation time. ``optional`` and ``default`` are in... */
  optional?: boolean | null;
  /** Must be ``collection``. */
  type: "collection";
  /** Collection type (defaults to `list` if `type` is `collection`). Nested collection types are separated with colons, e.g. `list:list:paired`. */
  collection_type?: null | string;
  /** Column schema for sample-sheet collection inputs. Only meaningful when `collection_type` begins with `sample_sheet` - cross-field validation is applied in the pydantic post-validator. */
  column_definitions?: null | Array<SampleSheetColumnDefinition>;
  /** Field schema for `record` collection inputs. Only meaningful when `collection_type` contains `record` (e.g. `record`, `list:record`, `sample_sheet:record`). */
  fields?: null | Array<RecordFieldDefinition>;
}

export interface MinMax {
  /** Minimum allowed value (inclusive). */
  min?: number | null;
  /** Maximum allowed value (inclusive). */
  max?: number | null;
}

/**
 * A scalar integer workflow parameter. Normalized gxformat2 output uses
``type: int``. ``type: integer`` is accepted for compatibility with native
Galaxy parameter state and Galaxy tool XML terminology.
 */
export interface WorkflowIntegerParameter extends BaseInputParameter, MinMax {
  /** The unique identifier for this object. */
  id?: null | string;
  /** A short, human-readable label of this object. */
  label?: null | string;
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc?: null | string | Array<string>;
  /** The default value to use for this parameter if the parameter is missing from the input object, or if the value of the parameter in the input object is `null`.  Default values are applied before eva... */
  default?: null | unknown;
  position?: null | StepPosition;
  /** Must be ``integer`` or ``int``. */
  type: "integer" | "int";
}

/**
 * A float input parameter for a Galaxy workflow.
 */
export interface WorkflowFloatParameter extends BaseInputParameter, MinMax {
  /** The unique identifier for this object. */
  id?: null | string;
  /** A short, human-readable label of this object. */
  label?: null | string;
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc?: null | string | Array<string>;
  /** The default value to use for this parameter if the parameter is missing from the input object, or if the value of the parameter in the input object is `null`.  Default values are applied before eva... */
  default?: null | unknown;
  position?: null | StepPosition;
  /** Must be ``float``. */
  type: "float";
}

/**
 * A scalar text workflow parameter. Normalized gxformat2 output uses
``type: string``. ``type: text`` is accepted for compatibility with native
Galaxy parameter state and Galaxy tool XML terminology.
 */
export interface WorkflowTextParameter extends BaseInputParameter {
  /** The unique identifier for this object. */
  id?: null | string;
  /** A short, human-readable label of this object. */
  label?: null | string;
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc?: null | string | Array<string>;
  /** The default value to use for this parameter if the parameter is missing from the input object, or if the value of the parameter in the input object is `null`.  Default values are applied before eva... */
  default?: null | unknown;
  position?: null | StepPosition;
  /** Must be ``text`` or ``string``. */
  type: "text" | "string";
  /** Closed set of permitted values. When present, Galaxy renders the runtime input as a select. Items may be plain strings or `{value, label}` records. */
  restrictions?: null | Array<string | WorkflowTextOption>;
  /** Open suggestion list. Galaxy still treats the input as text but offers these as suggestions. */
  suggestions?: null | Array<string | WorkflowTextOption>;
  /** Ask Galaxy to derive valid choices from connected tool or subworkflow select inputs at runtime. Falls back to free text when derivation fails. */
  restrictOnConnections?: null | boolean;
}

/**
 * A boolean input parameter for a Galaxy workflow.
 */
export interface WorkflowBooleanParameter extends BaseInputParameter {
  /** The unique identifier for this object. */
  id?: null | string;
  /** A short, human-readable label of this object. */
  label?: null | string;
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc?: null | string | Array<string>;
  /** The default value to use for this parameter if the parameter is missing from the input object, or if the value of the parameter in the input object is `null`.  Default values are applied before eva... */
  default?: null | unknown;
  position?: null | StepPosition;
  /** Must be ``boolean``. */
  type: "boolean";
}

/**
 * An input parameter to a Galaxy workflow. This is the catch-all type used
by the Schema Salad codegen. The pydantic layer uses a discriminated union
of the specific parameter types instead.
 */
export interface WorkflowInputParameter extends BaseDataParameter, MinMax {
  /** The unique identifier for this object. */
  id?: null | string;
  /** A short, human-readable label of this object. */
  label?: null | string;
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc?: null | string | Array<string>;
  /** The default value to use for this parameter if the parameter is missing from the input object, or if the value of the parameter in the input object is `null`.  Default values are applied before eva... */
  default?: null | unknown;
  position?: null | StepPosition;
  /** Controls whether Galaxy allows invocation of the workflow without a user-supplied value for this input. If ``true``, the input may be omitted at invocation time. ``optional`` and ``default`` are in... */
  optional?: boolean | null;
  /** Specify valid types of data that may be assigned to this parameter. */
  type?: GalaxyType | null | Array<GalaxyType>;
  /** Collection type (defaults to `list` if `type` is `collection`). Nested collection types are separated with colons, e.g. `list:list:paired`. */
  collection_type?: null | string;
  /** Column schema for sample-sheet collection inputs. Only meaningful when `collection_type` begins with `sample_sheet`. */
  column_definitions?: null | Array<SampleSheetColumnDefinition>;
  /** Field schema for `record` collection inputs. Only meaningful when `collection_type` contains `record`. */
  fields?: null | Array<RecordFieldDefinition>;
  /** Closed set of permitted values for text-typed inputs. See `WorkflowTextParameter.restrictions`. */
  restrictions?: null | Array<string | WorkflowTextOption>;
  /** Open suggestion list for text-typed inputs. */
  suggestions?: null | Array<string | WorkflowTextOption>;
  /** For text-typed inputs - derive runtime choices from connected tool/subworkflow select inputs. */
  restrictOnConnections?: null | boolean;
}

/**
 * Describe an output parameter of a workflow.  The parameter must be
connected to one parameter defined in the workflow that
will provide the value of the output parameter. It is legal to
connect a WorkflowInputParameter to a WorkflowOutputParameter.
 */
export interface WorkflowOutputParameter extends OutputParameter {
  /** The unique identifier for this object. */
  id?: null | string;
  /** A short, human-readable label of this object. */
  label?: null | string;
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc?: null | string | Array<string>;
  /** Specifies workflow parameter that supply the value of to the output parameter. */
  outputSource?: null | string;
  /** Specify valid types of data that may be assigned to this parameter. */
  type?: null | GalaxyType;
}

/**
 * This represents a non-input step a Galaxy Workflow.

# A note about `state` and `tool_state` fields.

Only one or the other should be specified. These are two ways to represent the "state"
of a tool at this workflow step. Both are essentially maps from parameter names to
parameter values.

`tool_state` is much more low-level and expects a flat dictionary with each value a JSON
dump. Nested tool structures such as conditionals and repeats should have all their values
in the JSON dumped string. In general `tool_state` may be present in workflows exported from
Galaxy but shouldn't be written by humans.

`state` can contained a typed map. Repeat values can be represented as YAML arrays. An alternative
to representing `state` this way is defining inputs with default values.
 */
export interface WorkflowStep
  extends Identified, Labeled, Documented, HasStepPosition, ReferencesTool, HasStepErrors, HasUUID {
  /** Defines the input parameters of the workflow step.  The process is ready to run when all required input parameters are associated with concrete values.  Input parameters include a schema for each p... */
  in?: Array<WorkflowStepInput> | Record<string, WorkflowStepInput | string | Array<string>> | null;
  /** Defines the parameters representing the output of the process.  May be used to generate and/or validate the output object.  This can also be called 'outputs' for legacy reasons - but the resulting ... */
  out?: Array<WorkflowStepOutput | string> | Record<string, WorkflowStepOutput | string> | null;
  /** Structured tool state. */
  state?: Record<string, unknown> | null;
  /** Unstructured tool state. */
  tool_state?: string | Record<string, unknown> | null;
  /** Optional dict of post-job actions keyed by ``{ActionType}{OutputName}`` compound strings.  Same shape as the native ``post_job_actions`` field; each value is a record with ``action_type``, ``output... */
  post_job_actions?: Record<string, unknown> | null;
  /** Workflow step module's type (defaults to 'tool'). */
  type?: null | WorkflowStepType;
  /** Specifies a subworkflow to run. May be an inline workflow definition, a URL string, or an @import reference dict. */
  run?: GalaxyWorkflow | string | Record<string, unknown> | null;
  runtime_inputs?: null | Array<string>;
  /** If defined, only run the step when the expression evaluates to `true`.  If `false` the step is skipped.  A skipped step produces a `null` on each output.  Expression should be an ecma5.1 expression. */
  when?: null | string;
}

export interface Sink {
  /** Specifies one or more workflow parameters that will provide input to the underlying step parameter. */
  source?: null | string | Array<string>;
}

/**
 * TODO:
 */
export interface WorkflowStepInput extends Identified, Sink, Labeled {
  /** The default value for this parameter to use if either there is no `source` field, or the value produced by the `source` is `null`.  The default must be applied prior to scattering or evaluating `va... */
  default?: null | unknown;
}

/**
 * Definition of an invocation report for this workflow. Currently the only
field is 'markdown'.
 */
export interface Report {
  /** Galaxy flavored Markdown to define an invocation report. */
  markdown: string;
}

/**
 * Associate an output parameter of the underlying process with a workflow
parameter.  The workflow parameter (given in the `id` field) be may be used
as a `source` to connect with input parameters of other workflow steps, or
with an output parameter of the process.

A unique identifier for this workflow output parameter.  This is
the identifier to use in the `source` field of `WorkflowStepInput`
to connect the output value to downstream parameters.
 */
export interface WorkflowStepOutput extends Identified {
  add_tags?: null | Array<string>;
  change_datatype?: null | string;
  delete_intermediate_datasets?: null | boolean;
  hide?: null | boolean;
  remove_tags?: null | Array<string>;
  rename?: null | string;
  set_columns?: Record<string, unknown> | null;
}

/**
 * Base fields shared by all comment types.
 */
export interface BaseComment {
  /** Position of the comment on the editor canvas as ``[x, y]`` coordinates. */
  position?: Array<number> | null;
  /** Size of the comment as ``[width, height]``. */
  size?: Array<number> | null;
  /** Display color of the comment (e.g. ``"none"``, ``"blue"``). */
  color?: null | string;
  /** Optional label for referencing this comment from frame ``contains_comments`` fields or for use as a map key when comments are represented as a mapping. */
  label?: null | string;
}

/**
 * A plain text annotation in the workflow editor.
 */
export interface TextComment extends BaseComment {
  /** Comment type (``text``). */
  type: "text";
  /** The text content. */
  text?: null | string;
  /** Whether the text is displayed in bold. */
  bold?: null | boolean;
  /** Whether the text is displayed in italic. */
  italic?: null | boolean;
  /** Font size of the text. */
  text_size?: null | number;
}

/**
 * A Markdown-rendered annotation in the workflow editor.
 */
export interface MarkdownComment extends BaseComment {
  /** Comment type (``markdown``). */
  type: "markdown";
  /** Markdown content. */
  text?: null | string;
}

/**
 * A rectangular grouping box that visually contains steps and other comments.
 */
export interface FrameComment extends BaseComment {
  /** Comment type (``frame``). */
  type: "frame";
  /** Title displayed on the frame header. */
  title?: null | string;
  /** Step labels or indices contained within this frame. */
  contains_steps?: null | Array<string | number>;
  /** Comment labels or indices contained within this frame. */
  contains_comments?: null | Array<string | number>;
}

/**
 * A freehand drawn line on the editor canvas.
 */
export interface FreehandComment extends BaseComment {
  /** Comment type (``freehand``). */
  type: "freehand";
  /** Line thickness. */
  thickness?: null | number;
  /** Array of ``[x, y]`` coordinate pairs defining the freehand line path. */
  line?: Array<Array<number>> | null;
}

/**
 * Base fields shared by all creator types, corresponding to schema.org
Thing properties common to both Person and Organization.
 */
export interface BaseCreator {
  /** Full name of the person or organization. */
  name?: null | string;
  /** Persistent identifier, typically an ORCID URL (e.g. ``https://orcid.org/0000-0001-2345-6789``) or bare ORCID. */
  identifier?: null | string;
  /** Website or profile URL. */
  url?: null | string;
  /** Email address. May include a ``mailto:`` prefix. */
  email?: null | string;
  /** URL to an image or avatar. */
  image?: null | string;
  /** Physical or mailing address. */
  address?: null | string;
  /** An alternate name or alias. */
  alternateName?: null | string;
  /** Telephone number. */
  telephone?: null | string;
  /** Fax number. */
  faxNumber?: null | string;
}

/**
 * A person who created or contributed to the workflow.
Corresponds to a `schema.org Person <https://schema.org/Person>`_.
 */
export interface CreatorPerson extends BaseCreator {
  /** Creator type discriminator (``Person``). */
  class: "Person";
  /** Given (first) name. */
  givenName?: null | string;
  /** Family (last) name. */
  familyName?: null | string;
  /** Honorific prefix (e.g. ``Dr``, ``Prof``). */
  honorificPrefix?: null | string;
  /** Honorific suffix (e.g. ``M.D.``, ``PhD``). */
  honorificSuffix?: null | string;
  /** Job title or role. */
  jobTitle?: null | string;
}

/**
 * An organization that created or contributed to the workflow.
Corresponds to a `schema.org Organization <https://schema.org/Organization>`_.
 */
export interface CreatorOrganization extends BaseCreator {
  /** Creator type discriminator (``Organization``). */
  class: "Organization";
}

/**
 * A Galaxy workflow description. This record corresponds to the description of a workflow that should be executable
on a Galaxy server that includes the contained tool definitions.

The workflows API or the user interface of Galaxy instances that are of version 19.09 or newer should be able to
import a document defining this record.

## A note about `label` field.

This is the name of the workflow in the Galaxy user interface. This is the mechanism that
users will primarily identify the workflow using. Legacy support - this may also be called 'name' and Galaxy will
consume the workflow document fine and treat this attribute correctly - however in order to validate against this
workflow definition schema the attribute should be called `label`.
 */
export interface GalaxyWorkflow extends Process, HasUUID {
  /** The unique identifier for this object. */
  id?: null | string;
  class: "GalaxyWorkflow";
  /** A short, human-readable label of this object. */
  label?: null | string;
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc?: null | string | Array<string>;
  /** The individual steps that make up the workflow. Each step is executed when all of its input data links are fulfilled. */
  steps: Array<WorkflowStep> | Record<string, WorkflowStep>;
  /** Workflow invocation report template. */
  report?: null | Report;
  /** Tags for the workflow. */
  tags?: Array<string> | null;
  /** Visual annotations for the workflow editor canvas. Comments are non-functional and do not affect workflow execution. May be specified as a list or as a mapping keyed by label. */
  comments?:
    | Array<TextComment | MarkdownComment | FrameComment | FreehandComment>
    | Record<string, TextComment | MarkdownComment | FrameComment | FreehandComment>
    | null;
  /** Workflow creators. Can be schema.org Person (https://schema.org/Person) or Organization (https://schema.org/Organization) entities. */
  creator?: Array<CreatorPerson | CreatorOrganization> | null;
  /** Must be a valid license listed at https://spdx.org/licenses/ */
  license?: null | string;
  /** If listed should correspond to the release of the workflow in its source reposiory. */
  release?: null | string;
}

export function isWorkflowDataParameter(
  v:
    | WorkflowDataParameter
    | WorkflowCollectionParameter
    | WorkflowIntegerParameter
    | WorkflowTextParameter
    | WorkflowFloatParameter
    | WorkflowBooleanParameter,
): v is WorkflowDataParameter {
  return v?.type === "data" || v?.type === "File";
}

export function isWorkflowCollectionParameter(
  v:
    | WorkflowDataParameter
    | WorkflowCollectionParameter
    | WorkflowIntegerParameter
    | WorkflowTextParameter
    | WorkflowFloatParameter
    | WorkflowBooleanParameter,
): v is WorkflowCollectionParameter {
  return v?.type === "collection";
}

export function isWorkflowIntegerParameter(
  v:
    | WorkflowDataParameter
    | WorkflowCollectionParameter
    | WorkflowIntegerParameter
    | WorkflowTextParameter
    | WorkflowFloatParameter
    | WorkflowBooleanParameter,
): v is WorkflowIntegerParameter {
  return v?.type === "integer" || v?.type === "int";
}

export function isWorkflowTextParameter(
  v:
    | WorkflowDataParameter
    | WorkflowCollectionParameter
    | WorkflowIntegerParameter
    | WorkflowTextParameter
    | WorkflowFloatParameter
    | WorkflowBooleanParameter,
): v is WorkflowTextParameter {
  return v?.type === "text" || v?.type === "string";
}

export function isWorkflowFloatParameter(
  v:
    | WorkflowDataParameter
    | WorkflowCollectionParameter
    | WorkflowIntegerParameter
    | WorkflowTextParameter
    | WorkflowFloatParameter
    | WorkflowBooleanParameter,
): v is WorkflowFloatParameter {
  return v?.type === "float";
}

export function isWorkflowBooleanParameter(
  v:
    | WorkflowDataParameter
    | WorkflowCollectionParameter
    | WorkflowIntegerParameter
    | WorkflowTextParameter
    | WorkflowFloatParameter
    | WorkflowBooleanParameter,
): v is WorkflowBooleanParameter {
  return v?.type === "boolean";
}
