// Auto-generated by schema-salad-plus-pydantic — do not edit.

/**
 * Salad data types are based on Avro schema declarations.  Refer to the
[Avro schema declaration documentation](https://avro.apache.org/docs/current/spec.html#schemas) for
detailed information.

null: no value
boolean: a binary value
int: 32-bit signed integer
long: 64-bit signed integer
float: single precision (32-bit) IEEE 754 floating-point number
double: double precision (64-bit) IEEE 754 floating-point number
string: Unicode character sequence
 */
export type PrimitiveType = "null" | "boolean" | "int" | "long" | "float" | "double" | "string";

/**
 * Step module types in the native Galaxy workflow format.
data_input: A single dataset input to the workflow.
data_collection_input: A dataset collection input to the workflow.
parameter_input: A typed parameter input (text, integer, float, boolean, color).
tool: A Galaxy tool execution step.
subworkflow: An embedded or referenced sub-workflow.
pause: A manual pause point that halts execution until user intervention.
pick_value: Select the first non-null value from multiple inputs.
 */
export type NativeStepType =
  | "data_input"
  | "data_collection_input"
  | "parameter_input"
  | "tool"
  | "subworkflow"
  | "pause"
  | "pick_value";

export interface Documented {
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc?: null | string | Array<string>;
}

/**
 * A field of a record.
 */
export interface RecordField extends Documented {
  /** The name of the field */
  name: string;
  /** The field type */
  type:
    | PrimitiveType
    | RecordSchema
    | EnumSchema
    | ArraySchema
    | string
    | Array<PrimitiveType | RecordSchema | EnumSchema | ArraySchema | string>;
}

export interface RecordSchema {
  /** Defines the fields of the record. */
  fields?: null | Array<RecordField>;
  /** Must be `record` */
  type: "record";
}

/**
 * Define an enumerated type.
 */
export interface EnumSchema {
  /** Defines the set of valid symbols. */
  symbols: Array<string>;
  /** Must be `enum` */
  type: "enum";
}

export interface ArraySchema {
  /** Defines the type of the array elements. */
  items:
    | PrimitiveType
    | RecordSchema
    | EnumSchema
    | ArraySchema
    | string
    | Array<PrimitiveType | RecordSchema | EnumSchema | ArraySchema | string>;
  /** Must be `array` */
  type: "array";
}

export interface HasUUID {
  /** UUID uniquely representing this element. */
  uuid?: null | string;
}

export interface HasStepErrors {
  /** During Galaxy export there may be some problem validating the tool state, tool used, etc.. that will be indicated by this field. The Galaxy user should be warned of these problems before the workfl... */
  errors?: null | string;
}

export interface HasStepPosition {
  position?: null | StepPosition;
}

/**
 * This field specifies the location of the step's node when rendered in the workflow editor.
 */
export interface StepPosition {
  /** Relative vertical position of the step's node when rendered in the workflow editor. */
  top: number;
  /** Relative horizontal position of the step's node when rendered in the workflow editor. */
  left: number;
}

export interface ReferencesTool {
  /** The tool ID used to run this step of the workflow (e.g. 'cat1' or 'toolshed.g2.bx.psu.edu/repos/nml/collapse_collections/collapse_dataset/4.0'). */
  tool_id?: null | string;
  /** The Galaxy Tool Shed repository that should be installed in order to use this tool. */
  tool_shed_repository?: null | ToolShedRepository;
  /** The tool version corresponding used to run this step of the workflow. For tool shed installed tools, the ID generally uniquely specifies a version and this field is optional. */
  tool_version?: null | string;
}

/**
 * Describes one column of a sample-sheet collection input.
Used in `column_definitions` on a `collection_type: sample_sheet[:<type>]`
workflow input.
 */
export interface SampleSheetColumnDefinition {
  /** Column name. Must not contain special characters (matches `^[\w\-_ \?]*$`). */
  name: string;
  /** Optional human-readable column description. */
  description?: null | string;
  /** Value type for this column. One of `string`, `int`, `float`, `boolean`, or `element_identifier`. Mirrors Galaxy's runtime `SampleSheetColumnType`. */
  type: "string" | "int" | "float" | "boolean" | "element_identifier";
  /** If true, rows may omit a value for this column. */
  optional: boolean;
  /** Default value used when a row omits this column. Type must be compatible with `type` - validated by the pydantic post-validator. */
  default_value?: null | string | number | boolean;
  /** Galaxy-style parameter validators. Modelled as opaque records here - full validator schema lives in galaxy.tool_util_models. */
  validators?: null | Array<unknown>;
  /** Closed set of permitted values for this column. Item type must be compatible with the column `type` (post-validated). */
  restrictions?: null | Array<string | number | number | boolean>;
  /** Open suggestion list for this column. */
  suggestions?: null | Array<string | number | number | boolean>;
}

/**
 * Describes one field of a `record` collection input.
Used in `fields` on a `collection_type` containing `record` (e.g.
`record`, `list:record`, `sample_sheet:record`). Mirrors a subset of
the CWL `InputRecordSchema` shape that Galaxy persists on
`DatasetCollection.fields`.
 */
export interface RecordFieldDefinition {
  /** Field name. Must equal the corresponding element identifier in the materialized record collection. */
  name: string;
  /** Field value type. A subset of the CWL primitive types: `File`, `null`, `boolean`, `int`, `float`, `string`. May be a list to express a union (e.g. `["File", "null"]` for an optional file). */
  type:
    | "File"
    | "null"
    | "boolean"
    | "int"
    | "float"
    | "string"
    | Array<"File" | "null" | "boolean" | "int" | "float" | "string">;
  /** Optional Galaxy datatype hint for `File`-typed fields. */
  format?: null | string;
}

/**
 * A `{value, label}` option used in `restrictions` or `suggestions` on a
text workflow parameter. Plain strings are also accepted in those
arrays as shorthand for `{value: <str>, label: <str>}`.
 */
export interface WorkflowTextOption {
  /** Machine value submitted to the connected tool input. */
  value: string;
  /** Human label shown in Galaxy. Defaults to `value` when omitted. */
  label?: null | string;
}

export interface ToolShedRepository {
  /** The name of the tool shed repository this tool can be found in. */
  name: string;
  /** The revision of the tool shed repository this tool can be found in. */
  changeset_revision: string;
  /** The owner of the tool shed repository this tool can be found in. */
  owner: string;
  /** The URI of the tool shed containing the repository this tool can be found in - typically this should be toolshed.g2.bx.psu.edu. */
  tool_shed: string;
}

/**
 * Describes an input parameter on a step. This is metadata about the input,
not the connection wiring (which is in ``input_connections``).
 */
export interface NativeStepInput {
  /** Name of the input parameter. */
  name: string;
  /** Human-readable description of this input. */
  description?: null | string;
}

/**
 * Declares an output produced by a step, with its name and datatype.
 */
export interface NativeStepOutput {
  /** Name of the output. */
  name: string;
  /** Galaxy datatype extension for the output (e.g. ``bam``, ``txt``, ``tabular``). The value ``input`` means the type is determined at runtime from the input data. */
  type?: null | string;
}

/**
 * Designates a step output as a workflow-level output. These appear in the
``workflow_outputs`` array on each step.
 */
export interface NativeWorkflowOutput {
  /** User-visible label for this workflow output. Must be unique across the workflow. */
  label?: null | string;
  /** Name of the step output to expose as a workflow output. */
  output_name: string;
  /** UUID for this workflow output. */
  uuid?: null | string;
}

/**
 * Describes a connection from one step's output to another step's input.
These objects appear as values in the ``input_connections`` dictionary.

For multi-valued inputs, the value is an array of these objects rather
than a single object.
 */
export interface NativeInputConnection {
  /** Step ID of the source step providing the data. */
  id: number;
  /** Name of the output on the source step (typically ``"output"`` for input steps). */
  output_name: string;
  /** For subworkflow steps, the internal step ID within the subworkflow that this connection routes to. Maps the parent connection to the correct input step inside the subworkflow. */
  input_subworkflow_step_id?: null | number;
}

/**
 * An action applied to a step's output after tool execution. These objects
appear as values in the ``post_job_actions`` dictionary, keyed by
compound strings of the form ``{ActionType}{OutputName}``
(e.g. ``HideDatasetActionout_pairs``).

Common action types: ``HideDatasetAction``, ``RenameDatasetAction``,
``DeleteIntermediatesAction``, ``ChangeDatatypeAction``,
``TagDatasetAction``, ``ColumnSetAction``.
 */
export interface NativePostJobAction {
  /** The action type identifier (e.g. ``HideDatasetAction``). */
  action_type: string;
  /** The step output this action applies to.  Optional: action types that operate on the step as a whole (e.g. ``ValidateOutputsAction``) omit this field. */
  output_name?: string | null;
  /** Action-specific arguments. For ``RenameDatasetAction``: ``{"newname": "..."}``; for ``ChangeDatatypeAction``: ``{"newtype": "tabular"}``; for ``TagDatasetAction``: ``{"tags": "name:tag"}``. Empty o... */
  action_arguments?: Record<string, unknown> | null;
}

/**
 * Data payload for a text comment.
 */
export interface NativeTextCommentData {
  /** The text content. */
  text?: null | string;
  /** Whether the text is displayed in bold. */
  bold?: null | boolean;
  /** Whether the text is displayed in italic. */
  italic?: null | boolean;
  /** Font size of the text. */
  size?: null | number;
}

/**
 * Data payload for a markdown comment.
 */
export interface NativeMarkdownCommentData {
  /** Markdown content. */
  text?: null | string;
}

/**
 * Data payload for a frame comment.
 */
export interface NativeFrameCommentData {
  /** Title displayed on the frame header. */
  title?: null | string;
}

/**
 * Data payload for a freehand comment.
 */
export interface NativeFreehandCommentData {
  /** Array of ``[x, y]`` coordinate pairs defining the freehand line path. */
  line?: Array<Array<number>> | null;
  /** Line thickness. */
  thickness?: null | number;
}

/**
 * Base fields shared by all comment types.
 */
export interface BaseNativeComment {
  /** Numeric identifier for this comment (order index). */
  id: number;
  /** Position on the editor canvas as ``[x, y]`` coordinates. */
  position?: Array<number> | null;
  /** Size as ``[width, height]``. */
  size?: Array<number> | null;
  /** Display color (e.g. ``"none"``, ``"blue"``). */
  color?: null | string;
}

/**
 * A plain text annotation in the workflow editor.
 */
export interface NativeTextComment extends BaseNativeComment {
  /** Comment type (``text``). */
  type: "text";
  /** Text content data: ``text``, ``bold``, ``italic``, ``size``. */
  data?: null | NativeTextCommentData;
}

/**
 * A Markdown-rendered annotation in the workflow editor.
 */
export interface NativeMarkdownComment extends BaseNativeComment {
  /** Comment type (``markdown``). */
  type: "markdown";
  /** Markdown content data: ``text``. */
  data?: null | NativeMarkdownCommentData;
}

/**
 * A rectangular grouping box that visually contains steps and other comments.
 */
export interface NativeFrameComment extends BaseNativeComment {
  /** Comment type (``frame``). */
  type: "frame";
  /** Frame content data: ``title``. */
  data?: null | NativeFrameCommentData;
  /** Step IDs contained within this frame. */
  child_steps?: null | Array<number>;
  /** Comment IDs contained within this frame. */
  child_comments?: null | Array<number>;
}

/**
 * A freehand drawn line on the editor canvas.
 */
export interface NativeFreehandComment extends BaseNativeComment {
  /** Comment type (``freehand``). */
  type: "freehand";
  /** Freehand content data: ``line``, ``thickness``. */
  data?: null | NativeFreehandCommentData;
}

/**
 * A step in a native Galaxy workflow. Steps are keyed by string integers
(``"0"``, ``"1"``, ...) in the ``steps`` dictionary. The key serves as
an external ID for connection wiring.

The ``type`` field determines the step's behavior. All step types share
common fields; type-specific fields are optional and only relevant for
their respective type.

# Tool State

The ``tool_state`` field contains the tool's parameter configuration.
Traditionally this is a JSON-encoded string (double-encoded: each top-level
value is itself a JSON string), but it may also be a plain dictionary when
unencoded tool state is used. Connected parameters are represented as
``{"__class__": "ConnectedValue"}``, runtime parameters as
``{"__class__": "RuntimeValue"}``.
 */
export interface NativeStep extends HasStepErrors, HasStepPosition, HasUUID, ReferencesTool {
  /** Display name. For tool steps this is the tool's name; for input steps it is the generic type name (e.g. "Input dataset"). */
  name?: null | string;
  /** Step ID. Matches the dictionary key in the ``steps`` object. */
  id?: null | number;
  /** Step module type. */
  type?: null | NativeStepType;
  /** User-friendly step label. Must be unique within the workflow. */
  label?: null | string;
  /** Human-readable step description. */
  annotation?: null | string;
  /** Conditional execution expression. Typically ``$(inputs.when)`` paired with a boolean input connection on the ``when`` key. */
  when?: null | string;
  /** Tool ID or content identifier. Same as ``tool_id`` for tool steps; may reference a subworkflow key for subworkflow steps. */
  content_id?: null | string;
  /** Tool parameter configuration. Traditionally a JSON-encoded string (double-encoded: each top-level value is itself a JSON string), but may also be a plain dict when ``encode_tool_state`` is disabled... */
  tool_state?: string | Record<string, unknown> | null;
  /** UUID for dynamic (inline-defined) tools. */
  tool_uuid?: null | string;
  /** Connection wiring from other steps' outputs to this step's inputs. Keys are input parameter names (using ``|`` for nested parameters). Values are a NativeInputConnection object or an array of them ... */
  input_connections?: Record<string, NativeInputConnection | Array<NativeInputConnection>> | null;
  /** Input parameter metadata (descriptions, not connections). */
  inputs?: null | Array<NativeStepInput>;
  /** Output declarations with names and datatypes. */
  outputs?: null | Array<NativeStepOutput>;
  /** Outputs designated as workflow-level outputs. Steps with an empty array have all their outputs hidden by default. */
  workflow_outputs?: null | Array<NativeWorkflowOutput>;
  /** Post-job actions applied to outputs after tool execution. Keys are compound strings of the form ``{ActionType}{OutputName}``. Values are NativePostJobAction objects. */
  post_job_actions?: Record<string, NativePostJobAction> | null;
  /** Embedded subworkflow definition. A complete native workflow document (with ``a_galaxy_workflow``, ``format-version``, ``steps``, etc.) nested inside this step. */
  subworkflow?: NativeGalaxyWorkflow | null;
  /** Embedded tool definition for user-defined (dynamic) tools. Present when the step uses a ``GalaxyUserTool`` instead of a registered tool. Contains the full tool definition including ``class: GalaxyU... */
  tool_representation?: Record<string, unknown> | null;
  /** Default values for step inputs. Keys are parameter names, values are objects with a ``default`` key. */
  in?: Record<string, unknown> | null;
}

/**
 * Workflow invocation report template.
 */
export interface NativeReport {
  /** Galaxy-flavored Markdown content for the invocation report. Supports template directives like ``history_dataset_as_image(output="...")``. */
  markdown: string;
}

/**
 * Base fields shared by all creator types, corresponding to schema.org
Thing properties common to both Person and Organization.
 */
export interface BaseNativeCreator {
  /** Full name of the person or organization. */
  name?: null | string;
  /** Persistent identifier, typically an ORCID URL (e.g. ``https://orcid.org/0000-0001-2345-6789``) or bare ORCID. */
  identifier?: null | string;
  /** Website or profile URL. */
  url?: null | string;
  /** Email address. May include a ``mailto:`` prefix. */
  email?: null | string;
  /** URL to an image or avatar. */
  image?: null | string;
  /** Physical or mailing address. */
  address?: null | string;
  /** An alternate name or alias. */
  alternateName?: null | string;
  /** Telephone number. */
  telephone?: null | string;
  /** Fax number. */
  faxNumber?: null | string;
}

/**
 * A person who created or contributed to the workflow.
Corresponds to a `schema.org Person <https://schema.org/Person>`_.
 */
export interface NativeCreatorPerson extends BaseNativeCreator {
  /** Creator type discriminator (``Person``). */
  class: "Person";
  /** Given (first) name. */
  givenName?: null | string;
  /** Family (last) name. */
  familyName?: null | string;
  /** Honorific prefix (e.g. ``Dr``, ``Prof``). */
  honorificPrefix?: null | string;
  /** Honorific suffix (e.g. ``M.D.``, ``PhD``). */
  honorificSuffix?: null | string;
  /** Job title or role. */
  jobTitle?: null | string;
}

/**
 * An organization that created or contributed to the workflow.
Corresponds to a `schema.org Organization <https://schema.org/Organization>`_.
 */
export interface NativeCreatorOrganization extends BaseNativeCreator {
  /** Creator type discriminator (``Organization``). */
  class: "Organization";
}

/**
 * Provenance tracking for workflows imported from external sources.
Contains either a direct URL or TRS (Tool Registry Service) metadata,
depending on how the workflow was imported.

For URL imports, only ``url`` is set. For TRS imports (Dockstore,
WorkflowHub), ``trs_tool_id``, ``trs_version_id``, and ``trs_url``
are set, with ``trs_server`` optionally identifying the server.
 */
export interface NativeSourceMetadata {
  /** URL from which the workflow was directly imported. */
  url?: null | string;
  /** Tool identifier in the Tool Registry Service (e.g. ``"#workflow/github.com/user/repo/workflow"`` or ``"109"``). */
  trs_tool_id?: null | string;
  /** Version identifier in the TRS (e.g. ``"master"``, ``"5"``). */
  trs_version_id?: null | string;
  /** TRS server name (e.g. ``"dockstore"``, ``"workflowhub"``). Optional even for TRS imports. */
  trs_server?: null | string;
  /** Complete TRS API endpoint URL for this workflow version. */
  trs_url?: null | string;
}

/**
 * A Galaxy native workflow document (.ga format). This is the canonical
serialization format used internally by Galaxy.

The native format mirrors the database schema directly -- steps are keyed
by numeric IDs, connections reference step IDs, and tool state is stored
as double-encoded JSON strings.

The format version has been ``"0.1"`` since inception. New features are
added without version bumps.
 */
export interface NativeGalaxyWorkflow extends HasUUID {
  /** Workflow display name. */
  name?: null | string;
  class: "NativeGalaxyWorkflow";
  /** Format marker. Always the string ``"true"``. */
  a_galaxy_workflow: "true";
  /** Format version. Always ``"0.1"`` currently. In the JSON document this field is written as ``format-version``. */
  "format-version": "0.1";
  /** Human-readable workflow description. */
  annotation?: null | string;
  /** Classification tags for the workflow. */
  tags?: null | Array<string>;
  /** Internal revision counter. */
  version?: null | number;
  /** SPDX license identifier (e.g. ``"MIT"``, ``"CC-BY-4.0"``). */
  license?: null | string;
  /** Semantic version for published workflows. */
  release?: null | string;
  /** Creator(s) of this workflow. An array of schema.org NativeCreatorPerson or NativeCreatorOrganization objects, dispatched via the ``class`` field (``Person`` or ``Organization``). */
  creator?: Array<NativeCreatorPerson | NativeCreatorOrganization> | null;
  /** Workflow invocation report template. */
  report?: null | NativeReport;
  /** Detailed workflow description in Markdown. */
  readme?: null | string;
  /** Help text in Markdown. */
  help?: null | string;
  /** URL to workflow logo image. */
  logo_url?: null | string;
  /** Associated DOIs. */
  doi?: null | Array<string>;
  /** Provenance tracking metadata for workflows imported from TRS or URLs. */
  source_metadata?: null | NativeSourceMetadata;
  /** Visual annotations in the workflow editor. */
  comments?: Array<
    NativeTextComment | NativeMarkdownComment | NativeFrameComment | NativeFreehandComment
  > | null;
  /** Step dictionary keyed by string integers (``"0"``, ``"1"``, ...). Values are NativeStep objects. Steps are processed in sorted numeric order during import. */
  steps?: Record<string, NativeStep> | null;
  /** Map of locally-defined subworkflow dicts, used during format conversion. */
  subworkflows?: Record<string, NativeGalaxyWorkflow> | null;
}

export function isNativeCreatorPerson(
  v: NativeCreatorPerson | NativeCreatorOrganization,
): v is NativeCreatorPerson {
  return v?.class === "Person";
}

export function isNativeCreatorOrganization(
  v: NativeCreatorPerson | NativeCreatorOrganization,
): v is NativeCreatorOrganization {
  return v?.class === "Organization";
}

export function isNativeTextComment(
  v: NativeTextComment | NativeMarkdownComment | NativeFrameComment | NativeFreehandComment,
): v is NativeTextComment {
  return v?.type === "text";
}

export function isNativeMarkdownComment(
  v: NativeTextComment | NativeMarkdownComment | NativeFrameComment | NativeFreehandComment,
): v is NativeMarkdownComment {
  return v?.type === "markdown";
}

export function isNativeFrameComment(
  v: NativeTextComment | NativeMarkdownComment | NativeFrameComment | NativeFreehandComment,
): v is NativeFrameComment {
  return v?.type === "frame";
}

export function isNativeFreehandComment(
  v: NativeTextComment | NativeMarkdownComment | NativeFrameComment | NativeFreehandComment,
): v is NativeFreehandComment {
  return v?.type === "freehand";
}
