// Auto-generated by schema-salad-plus-pydantic — do not edit.

import { Schema } from "effect";

/**
 * Salad data types are based on Avro schema declarations.  Refer to the
[Avro schema declaration documentation](https://avro.apache.org/docs/current/spec.html#schemas) for
detailed information.

null: no value
boolean: a binary value
int: 32-bit signed integer
long: 64-bit signed integer
float: single precision (32-bit) IEEE 754 floating-point number
double: double precision (64-bit) IEEE 754 floating-point number
string: Unicode character sequence
 */
export const PrimitiveTypeSchema = Schema.Literal(
  "null",
  "boolean",
  "int",
  "long",
  "float",
  "double",
  "string",
);
export type PrimitiveType = typeof PrimitiveTypeSchema.Type;

/**
 * Step module types in the native Galaxy workflow format.
data_input: A single dataset input to the workflow.
data_collection_input: A dataset collection input to the workflow.
parameter_input: A typed parameter input (text, integer, float, boolean, color).
tool: A Galaxy tool execution step.
subworkflow: An embedded or referenced sub-workflow.
pause: A manual pause point that halts execution until user intervention.
pick_value: Select the first non-null value from multiple inputs.
 */
export const NativeStepTypeSchema = Schema.Literal(
  "data_input",
  "data_collection_input",
  "parameter_input",
  "tool",
  "subworkflow",
  "pause",
  "pick_value",
);
export type NativeStepType = typeof NativeStepTypeSchema.Type;

export const DocumentedSchema = Schema.Struct({
  /** A documentation string for this object, or an array of strings which should be concatenated. */
  doc: Schema.optional(Schema.Union(Schema.Null, Schema.String, Schema.Array(Schema.String))),
});
export type Documented = typeof DocumentedSchema.Type;

export const RecordSchemaSchema = Schema.Struct({
  /** Defines the fields of the record. */
  fields: Schema.optional(
    Schema.Union(
      Schema.Null,
      Schema.Array(
        Schema.suspend((): Schema.Schema<any> => RecordFieldSchema).annotations({
          identifier: "RecordFieldSchema",
        }),
      ),
    ),
  ),
  /** Must be `record` */
  type: Schema.Literal("record"),
});
export type RecordSchema = typeof RecordSchemaSchema.Type;

/**
 * Define an enumerated type.
 */
export const EnumSchemaSchema = Schema.Struct({
  /** Defines the set of valid symbols. */
  symbols: Schema.Array(Schema.String),
  /** Must be `enum` */
  type: Schema.Literal("enum"),
});
export type EnumSchema = typeof EnumSchemaSchema.Type;

export const ArraySchemaSchema = Schema.Struct({
  /** Defines the type of the array elements. */
  items: Schema.Union(
    PrimitiveTypeSchema,
    RecordSchemaSchema,
    EnumSchemaSchema,
    Schema.suspend((): Schema.Schema<any> => ArraySchemaSchema).annotations({
      identifier: "ArraySchemaSchema",
    }),
    Schema.String,
    Schema.Array(
      Schema.Union(
        PrimitiveTypeSchema,
        RecordSchemaSchema,
        EnumSchemaSchema,
        Schema.suspend((): Schema.Schema<any> => ArraySchemaSchema).annotations({
          identifier: "ArraySchemaSchema",
        }),
        Schema.String,
      ),
    ),
  ),
  /** Must be `array` */
  type: Schema.Literal("array"),
});
export type ArraySchema = typeof ArraySchemaSchema.Type;

/**
 * A field of a record.
 */
export const RecordFieldSchema = Schema.Struct({
  ...DocumentedSchema.fields,
  /** The name of the field */
  name: Schema.String,
  /** The field type */
  type: Schema.Union(
    PrimitiveTypeSchema,
    RecordSchemaSchema,
    EnumSchemaSchema,
    ArraySchemaSchema,
    Schema.String,
    Schema.Array(
      Schema.Union(
        PrimitiveTypeSchema,
        RecordSchemaSchema,
        EnumSchemaSchema,
        ArraySchemaSchema,
        Schema.String,
      ),
    ),
  ),
});
export type RecordField = typeof RecordFieldSchema.Type;

export const HasUUIDSchema = Schema.Struct({
  /** UUID uniquely representing this element. */
  uuid: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type HasUUID = typeof HasUUIDSchema.Type;

export const HasStepErrorsSchema = Schema.Struct({
  /** During Galaxy export there may be some problem validating the tool state, tool used, etc.. that will be indicated by this field. The Galaxy user should be warned of these problems before the workfl... */
  errors: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type HasStepErrors = typeof HasStepErrorsSchema.Type;

/**
 * This field specifies the location of the step's node when rendered in the workflow editor.
 */
export const StepPositionSchema = Schema.Struct({
  /** Relative vertical position of the step's node when rendered in the workflow editor. */
  top: Schema.Number,
  /** Relative horizontal position of the step's node when rendered in the workflow editor. */
  left: Schema.Number,
});
export type StepPosition = typeof StepPositionSchema.Type;

export const HasStepPositionSchema = Schema.Struct({
  position: Schema.optional(Schema.Union(Schema.Null, StepPositionSchema)),
});
export type HasStepPosition = typeof HasStepPositionSchema.Type;

export const ToolShedRepositorySchema = Schema.Struct({
  /** The name of the tool shed repository this tool can be found in. */
  name: Schema.String,
  /** The revision of the tool shed repository this tool can be found in. */
  changeset_revision: Schema.String,
  /** The owner of the tool shed repository this tool can be found in. */
  owner: Schema.String,
  /** The URI of the tool shed containing the repository this tool can be found in - typically this should be toolshed.g2.bx.psu.edu. */
  tool_shed: Schema.String,
});
export type ToolShedRepository = typeof ToolShedRepositorySchema.Type;

export const ReferencesToolSchema = Schema.Struct({
  /** The tool ID used to run this step of the workflow (e.g. 'cat1' or 'toolshed.g2.bx.psu.edu/repos/nml/collapse_collections/collapse_dataset/4.0'). */
  tool_id: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** The Galaxy Tool Shed repository that should be installed in order to use this tool. */
  tool_shed_repository: Schema.optional(Schema.Union(Schema.Null, ToolShedRepositorySchema)),
  /** The tool version corresponding used to run this step of the workflow. For tool shed installed tools, the ID generally uniquely specifies a version and this field is optional. */
  tool_version: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type ReferencesTool = typeof ReferencesToolSchema.Type;

/**
 * Describes one column of a sample-sheet collection input.
Used in `column_definitions` on a `collection_type: sample_sheet[:<type>]`
workflow input.
 */
export const SampleSheetColumnDefinitionSchema = Schema.Struct({
  /** Column name. Must not contain special characters (matches `^[\w\-_ \?]*$`). */
  name: Schema.String,
  /** Optional human-readable column description. */
  description: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Value type for this column. One of `string`, `int`, `float`, `boolean`, or `element_identifier`. Mirrors Galaxy's runtime `SampleSheetColumnType`. */
  type: Schema.Literal("string", "int", "float", "boolean", "element_identifier"),
  /** If true, rows may omit a value for this column. */
  optional: Schema.Boolean,
  /** Default value used when a row omits this column. Type must be compatible with `type` - validated by the pydantic post-validator. */
  default_value: Schema.optional(
    Schema.Union(Schema.Null, Schema.String, Schema.Number, Schema.Boolean),
  ),
  /** Galaxy-style parameter validators. Modelled as opaque records here - full validator schema lives in galaxy.tool_util_models. */
  validators: Schema.optional(Schema.Union(Schema.Null, Schema.Array(Schema.Unknown))),
  /** Closed set of permitted values for this column. Item type must be compatible with the column `type` (post-validated). */
  restrictions: Schema.optional(
    Schema.Union(
      Schema.Null,
      Schema.Array(Schema.Union(Schema.String, Schema.Number, Schema.Number, Schema.Boolean)),
    ),
  ),
  /** Open suggestion list for this column. */
  suggestions: Schema.optional(
    Schema.Union(
      Schema.Null,
      Schema.Array(Schema.Union(Schema.String, Schema.Number, Schema.Number, Schema.Boolean)),
    ),
  ),
});
export type SampleSheetColumnDefinition = typeof SampleSheetColumnDefinitionSchema.Type;

/**
 * Describes one field of a `record` collection input.
Used in `fields` on a `collection_type` containing `record` (e.g.
`record`, `list:record`, `sample_sheet:record`). Mirrors a subset of
the CWL `InputRecordSchema` shape that Galaxy persists on
`DatasetCollection.fields`.
 */
export const RecordFieldDefinitionSchema = Schema.Struct({
  /** Field name. Must equal the corresponding element identifier in the materialized record collection. */
  name: Schema.String,
  /** Field value type. A subset of the CWL primitive types: `File`, `null`, `boolean`, `int`, `float`, `string`. May be a list to express a union (e.g. `["File", "null"]` for an optional file). */
  type: Schema.Union(
    Schema.Literal("File", "null", "boolean", "int", "float", "string"),
    Schema.Array(Schema.Literal("File", "null", "boolean", "int", "float", "string")),
  ),
  /** Optional Galaxy datatype hint for `File`-typed fields. */
  format: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type RecordFieldDefinition = typeof RecordFieldDefinitionSchema.Type;

/**
 * A `{value, label}` option used in `restrictions` or `suggestions` on a
text workflow parameter. Plain strings are also accepted in those
arrays as shorthand for `{value: <str>, label: <str>}`.
 */
export const WorkflowTextOptionSchema = Schema.Struct({
  /** Machine value submitted to the connected tool input. */
  value: Schema.String,
  /** Human label shown in Galaxy. Defaults to `value` when omitted. */
  label: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type WorkflowTextOption = typeof WorkflowTextOptionSchema.Type;

/**
 * Describes an input parameter on a step. This is metadata about the input,
not the connection wiring (which is in ``input_connections``).
 */
export const NativeStepInputSchema = Schema.Struct({
  /** Name of the input parameter. */
  name: Schema.String,
  /** Human-readable description of this input. */
  description: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type NativeStepInput = typeof NativeStepInputSchema.Type;

/**
 * Declares an output produced by a step, with its name and datatype.
 */
export const NativeStepOutputSchema = Schema.Struct({
  /** Name of the output. */
  name: Schema.String,
  /** Galaxy datatype extension for the output (e.g. ``bam``, ``txt``, ``tabular``). The value ``input`` means the type is determined at runtime from the input data. */
  type: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type NativeStepOutput = typeof NativeStepOutputSchema.Type;

/**
 * Designates a step output as a workflow-level output. These appear in the
``workflow_outputs`` array on each step.
 */
export const NativeWorkflowOutputSchema = Schema.Struct({
  /** User-visible label for this workflow output. Must be unique across the workflow. */
  label: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Name of the step output to expose as a workflow output. */
  output_name: Schema.String,
  /** UUID for this workflow output. */
  uuid: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type NativeWorkflowOutput = typeof NativeWorkflowOutputSchema.Type;

/**
 * Describes a connection from one step's output to another step's input.
These objects appear as values in the ``input_connections`` dictionary.

For multi-valued inputs, the value is an array of these objects rather
than a single object.
 */
export const NativeInputConnectionSchema = Schema.Struct({
  /** Step ID of the source step providing the data. */
  id: Schema.Number,
  /** Name of the output on the source step (typically ``"output"`` for input steps). */
  output_name: Schema.String,
  /** For subworkflow steps, the internal step ID within the subworkflow that this connection routes to. Maps the parent connection to the correct input step inside the subworkflow. */
  input_subworkflow_step_id: Schema.optional(Schema.Union(Schema.Null, Schema.Number)),
});
export type NativeInputConnection = typeof NativeInputConnectionSchema.Type;

/**
 * An action applied to a step's output after tool execution. These objects
appear as values in the ``post_job_actions`` dictionary, keyed by
compound strings of the form ``{ActionType}{OutputName}``
(e.g. ``HideDatasetActionout_pairs``).

Common action types: ``HideDatasetAction``, ``RenameDatasetAction``,
``DeleteIntermediatesAction``, ``ChangeDatatypeAction``,
``TagDatasetAction``, ``ColumnSetAction``.
 */
export const NativePostJobActionSchema = Schema.Struct({
  /** The action type identifier (e.g. ``HideDatasetAction``). */
  action_type: Schema.String,
  /** The step output this action applies to.  Optional: action types that operate on the step as a whole (e.g. ``ValidateOutputsAction``) omit this field. */
  output_name: Schema.optional(Schema.Union(Schema.String, Schema.Null)),
  /** Action-specific arguments. For ``RenameDatasetAction``: ``{"newname": "..."}``; for ``ChangeDatatypeAction``: ``{"newtype": "tabular"}``; for ``TagDatasetAction``: ``{"tags": "name:tag"}``. Empty o... */
  action_arguments: Schema.optional(
    Schema.Union(Schema.Record({ key: Schema.String, value: Schema.Unknown }), Schema.Null),
  ),
});
export type NativePostJobAction = typeof NativePostJobActionSchema.Type;

/**
 * Data payload for a text comment.
 */
export const NativeTextCommentDataSchema = Schema.Struct({
  /** The text content. */
  text: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Whether the text is displayed in bold. */
  bold: Schema.optional(Schema.Union(Schema.Null, Schema.Boolean)),
  /** Whether the text is displayed in italic. */
  italic: Schema.optional(Schema.Union(Schema.Null, Schema.Boolean)),
  /** Font size of the text. */
  size: Schema.optional(Schema.Union(Schema.Null, Schema.Number)),
});
export type NativeTextCommentData = typeof NativeTextCommentDataSchema.Type;

/**
 * Data payload for a markdown comment.
 */
export const NativeMarkdownCommentDataSchema = Schema.Struct({
  /** Markdown content. */
  text: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type NativeMarkdownCommentData = typeof NativeMarkdownCommentDataSchema.Type;

/**
 * Data payload for a frame comment.
 */
export const NativeFrameCommentDataSchema = Schema.Struct({
  /** Title displayed on the frame header. */
  title: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type NativeFrameCommentData = typeof NativeFrameCommentDataSchema.Type;

/**
 * Data payload for a freehand comment.
 */
export const NativeFreehandCommentDataSchema = Schema.Struct({
  /** Array of ``[x, y]`` coordinate pairs defining the freehand line path. */
  line: Schema.optional(Schema.Union(Schema.Array(Schema.Array(Schema.Number)), Schema.Null)),
  /** Line thickness. */
  thickness: Schema.optional(Schema.Union(Schema.Null, Schema.Number)),
});
export type NativeFreehandCommentData = typeof NativeFreehandCommentDataSchema.Type;

/**
 * Base fields shared by all comment types.
 */
export const BaseNativeCommentSchema = Schema.Struct({
  /** Numeric identifier for this comment (order index). */
  id: Schema.Number,
  /** Position on the editor canvas as ``[x, y]`` coordinates. */
  position: Schema.optional(Schema.Union(Schema.Array(Schema.Number), Schema.Null)),
  /** Size as ``[width, height]``. */
  size: Schema.optional(Schema.Union(Schema.Array(Schema.Number), Schema.Null)),
  /** Display color (e.g. ``"none"``, ``"blue"``). */
  color: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type BaseNativeComment = typeof BaseNativeCommentSchema.Type;

/**
 * A plain text annotation in the workflow editor.
 */
export const NativeTextCommentSchema = Schema.Struct({
  ...BaseNativeCommentSchema.fields,
  /** Comment type (``text``). */
  type: Schema.Literal("text"),
  /** Text content data: ``text``, ``bold``, ``italic``, ``size``. */
  data: Schema.optional(Schema.Union(Schema.Null, NativeTextCommentDataSchema)),
});
export type NativeTextComment = typeof NativeTextCommentSchema.Type;

/**
 * A Markdown-rendered annotation in the workflow editor.
 */
export const NativeMarkdownCommentSchema = Schema.Struct({
  ...BaseNativeCommentSchema.fields,
  /** Comment type (``markdown``). */
  type: Schema.Literal("markdown"),
  /** Markdown content data: ``text``. */
  data: Schema.optional(Schema.Union(Schema.Null, NativeMarkdownCommentDataSchema)),
});
export type NativeMarkdownComment = typeof NativeMarkdownCommentSchema.Type;

/**
 * A rectangular grouping box that visually contains steps and other comments.
 */
export const NativeFrameCommentSchema = Schema.Struct({
  ...BaseNativeCommentSchema.fields,
  /** Comment type (``frame``). */
  type: Schema.Literal("frame"),
  /** Frame content data: ``title``. */
  data: Schema.optional(Schema.Union(Schema.Null, NativeFrameCommentDataSchema)),
  /** Step IDs contained within this frame. */
  child_steps: Schema.optional(Schema.Union(Schema.Null, Schema.Array(Schema.Number))),
  /** Comment IDs contained within this frame. */
  child_comments: Schema.optional(Schema.Union(Schema.Null, Schema.Array(Schema.Number))),
});
export type NativeFrameComment = typeof NativeFrameCommentSchema.Type;

/**
 * A freehand drawn line on the editor canvas.
 */
export const NativeFreehandCommentSchema = Schema.Struct({
  ...BaseNativeCommentSchema.fields,
  /** Comment type (``freehand``). */
  type: Schema.Literal("freehand"),
  /** Freehand content data: ``line``, ``thickness``. */
  data: Schema.optional(Schema.Union(Schema.Null, NativeFreehandCommentDataSchema)),
});
export type NativeFreehandComment = typeof NativeFreehandCommentSchema.Type;

/**
 * Workflow invocation report template.
 */
export const NativeReportSchema = Schema.Struct({
  /** Galaxy-flavored Markdown content for the invocation report. Supports template directives like ``history_dataset_as_image(output="...")``. */
  markdown: Schema.String,
});
export type NativeReport = typeof NativeReportSchema.Type;

/**
 * Provenance tracking for workflows imported from external sources.
Contains either a direct URL or TRS (Tool Registry Service) metadata,
depending on how the workflow was imported.

For URL imports, only ``url`` is set. For TRS imports (Dockstore,
WorkflowHub), ``trs_tool_id``, ``trs_version_id``, and ``trs_url``
are set, with ``trs_server`` optionally identifying the server.
 */
export const NativeSourceMetadataSchema = Schema.Struct({
  /** URL from which the workflow was directly imported. */
  url: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Tool identifier in the Tool Registry Service (e.g. ``"#workflow/github.com/user/repo/workflow"`` or ``"109"``). */
  trs_tool_id: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Version identifier in the TRS (e.g. ``"master"``, ``"5"``). */
  trs_version_id: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** TRS server name (e.g. ``"dockstore"``, ``"workflowhub"``). Optional even for TRS imports. */
  trs_server: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Complete TRS API endpoint URL for this workflow version. */
  trs_url: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type NativeSourceMetadata = typeof NativeSourceMetadataSchema.Type;

/**
 * Base fields shared by all creator types, corresponding to schema.org
Thing properties common to both Person and Organization.
 */
export const BaseNativeCreatorSchema = Schema.Struct({
  /** Full name of the person or organization. */
  name: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Persistent identifier, typically an ORCID URL (e.g. ``https://orcid.org/0000-0001-2345-6789``) or bare ORCID. */
  identifier: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Website or profile URL. */
  url: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Email address. May include a ``mailto:`` prefix. */
  email: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** URL to an image or avatar. */
  image: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Physical or mailing address. */
  address: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** An alternate name or alias. */
  alternateName: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Telephone number. */
  telephone: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Fax number. */
  faxNumber: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type BaseNativeCreator = typeof BaseNativeCreatorSchema.Type;

/**
 * An organization that created or contributed to the workflow.
Corresponds to a `schema.org Organization <https://schema.org/Organization>`_.
 */
export const NativeCreatorOrganizationSchema = Schema.Struct({
  ...BaseNativeCreatorSchema.fields,
  /** Creator type discriminator (``Organization``). */
  class: Schema.Literal("Organization"),
});
export type NativeCreatorOrganization = typeof NativeCreatorOrganizationSchema.Type;

/**
 * A person who created or contributed to the workflow.
Corresponds to a `schema.org Person <https://schema.org/Person>`_.
 */
export const NativeCreatorPersonSchema = Schema.Struct({
  ...BaseNativeCreatorSchema.fields,
  /** Creator type discriminator (``Person``). */
  class: Schema.Literal("Person"),
  /** Given (first) name. */
  givenName: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Family (last) name. */
  familyName: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Honorific prefix (e.g. ``Dr``, ``Prof``). */
  honorificPrefix: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Honorific suffix (e.g. ``M.D.``, ``PhD``). */
  honorificSuffix: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Job title or role. */
  jobTitle: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
});
export type NativeCreatorPerson = typeof NativeCreatorPersonSchema.Type;

/**
 * A Galaxy native workflow document (.ga format). This is the canonical
serialization format used internally by Galaxy.

The native format mirrors the database schema directly -- steps are keyed
by numeric IDs, connections reference step IDs, and tool state is stored
as double-encoded JSON strings.

The format version has been ``"0.1"`` since inception. New features are
added without version bumps.
 */
export const NativeGalaxyWorkflowSchema = Schema.Struct({
  ...HasUUIDSchema.fields,
  /** Workflow display name. */
  name: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  class: Schema.Literal("NativeGalaxyWorkflow"),
  /** Format marker. Always the string ``"true"``. */
  a_galaxy_workflow: Schema.Literal("true"),
  /** Format version. Always ``"0.1"`` currently. In the JSON document this field is written as ``format-version``. */
  "format-version": Schema.Literal("0.1"),
  /** Human-readable workflow description. */
  annotation: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Classification tags for the workflow. */
  tags: Schema.optional(Schema.Union(Schema.Null, Schema.Array(Schema.String))),
  /** Internal revision counter. */
  version: Schema.optional(Schema.Union(Schema.Null, Schema.Number)),
  /** SPDX license identifier (e.g. ``"MIT"``, ``"CC-BY-4.0"``). */
  license: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Semantic version for published workflows. */
  release: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Creator(s) of this workflow. An array of schema.org NativeCreatorPerson or NativeCreatorOrganization objects, dispatched via the ``class`` field (``Person`` or ``Organization``). */
  creator: Schema.optional(
    Schema.Union(
      Schema.Array(Schema.Union(NativeCreatorPersonSchema, NativeCreatorOrganizationSchema)),
      Schema.Null,
    ),
  ),
  /** Workflow invocation report template. */
  report: Schema.optional(Schema.Union(Schema.Null, NativeReportSchema)),
  /** Detailed workflow description in Markdown. */
  readme: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Help text in Markdown. */
  help: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** URL to workflow logo image. */
  logo_url: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Associated DOIs. */
  doi: Schema.optional(Schema.Union(Schema.Null, Schema.Array(Schema.String))),
  /** Provenance tracking metadata for workflows imported from TRS or URLs. */
  source_metadata: Schema.optional(Schema.Union(Schema.Null, NativeSourceMetadataSchema)),
  /** Visual annotations in the workflow editor. */
  comments: Schema.optional(
    Schema.Union(
      Schema.Array(
        Schema.Union(
          NativeTextCommentSchema,
          NativeMarkdownCommentSchema,
          NativeFrameCommentSchema,
          NativeFreehandCommentSchema,
        ),
      ),
      Schema.Null,
    ),
  ),
  /** Step dictionary keyed by string integers (``"0"``, ``"1"``, ...). Values are NativeStep objects. Steps are processed in sorted numeric order during import. */
  steps: Schema.optional(
    Schema.Union(
      Schema.Record({
        key: Schema.String,
        value: Schema.suspend((): Schema.Schema<any> => NativeStepSchema).annotations({
          identifier: "NativeStepSchema",
        }),
      }),
      Schema.Null,
    ),
  ),
  /** Map of locally-defined subworkflow dicts, used during format conversion. */
  subworkflows: Schema.optional(
    Schema.Union(
      Schema.Record({
        key: Schema.String,
        value: Schema.suspend((): Schema.Schema<any> => NativeGalaxyWorkflowSchema).annotations({
          identifier: "NativeGalaxyWorkflowSchema",
        }),
      }),
      Schema.Null,
    ),
  ),
});
export type NativeGalaxyWorkflow = typeof NativeGalaxyWorkflowSchema.Type;

/**
 * A step in a native Galaxy workflow. Steps are keyed by string integers
(``"0"``, ``"1"``, ...) in the ``steps`` dictionary. The key serves as
an external ID for connection wiring.

The ``type`` field determines the step's behavior. All step types share
common fields; type-specific fields are optional and only relevant for
their respective type.

# Tool State

The ``tool_state`` field contains the tool's parameter configuration.
Traditionally this is a JSON-encoded string (double-encoded: each top-level
value is itself a JSON string), but it may also be a plain dictionary when
unencoded tool state is used. Connected parameters are represented as
``{"__class__": "ConnectedValue"}``, runtime parameters as
``{"__class__": "RuntimeValue"}``.
 */
export const NativeStepSchema = Schema.Struct({
  ...HasStepErrorsSchema.fields,
  ...HasStepPositionSchema.fields,
  ...HasUUIDSchema.fields,
  ...ReferencesToolSchema.fields,
  /** Display name. For tool steps this is the tool's name; for input steps it is the generic type name (e.g. "Input dataset"). */
  name: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Step ID. Matches the dictionary key in the ``steps`` object. */
  id: Schema.optional(Schema.Union(Schema.Null, Schema.Number)),
  /** Step module type. */
  type: Schema.optional(Schema.Union(Schema.Null, NativeStepTypeSchema)),
  /** User-friendly step label. Must be unique within the workflow. */
  label: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Human-readable step description. */
  annotation: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Conditional execution expression. Typically ``$(inputs.when)`` paired with a boolean input connection on the ``when`` key. */
  when: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Tool ID or content identifier. Same as ``tool_id`` for tool steps; may reference a subworkflow key for subworkflow steps. */
  content_id: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Tool parameter configuration. Traditionally a JSON-encoded string (double-encoded: each top-level value is itself a JSON string), but may also be a plain dict when ``encode_tool_state`` is disabled... */
  tool_state: Schema.optional(
    Schema.Union(
      Schema.String,
      Schema.Record({ key: Schema.String, value: Schema.Unknown }),
      Schema.Null,
    ),
  ),
  /** UUID for dynamic (inline-defined) tools. */
  tool_uuid: Schema.optional(Schema.Union(Schema.Null, Schema.String)),
  /** Connection wiring from other steps' outputs to this step's inputs. Keys are input parameter names (using ``|`` for nested parameters). Values are a NativeInputConnection object or an array of them ... */
  input_connections: Schema.optional(
    Schema.Union(
      Schema.Record({
        key: Schema.String,
        value: Schema.Union(NativeInputConnectionSchema, Schema.Array(NativeInputConnectionSchema)),
      }),
      Schema.Null,
    ),
  ),
  /** Input parameter metadata (descriptions, not connections). */
  inputs: Schema.optional(Schema.Union(Schema.Null, Schema.Array(NativeStepInputSchema))),
  /** Output declarations with names and datatypes. */
  outputs: Schema.optional(Schema.Union(Schema.Null, Schema.Array(NativeStepOutputSchema))),
  /** Outputs designated as workflow-level outputs. Steps with an empty array have all their outputs hidden by default. */
  workflow_outputs: Schema.optional(
    Schema.Union(Schema.Null, Schema.Array(NativeWorkflowOutputSchema)),
  ),
  /** Post-job actions applied to outputs after tool execution. Keys are compound strings of the form ``{ActionType}{OutputName}``. Values are NativePostJobAction objects. */
  post_job_actions: Schema.optional(
    Schema.Union(
      Schema.Record({ key: Schema.String, value: NativePostJobActionSchema }),
      Schema.Null,
    ),
  ),
  /** Embedded subworkflow definition. A complete native workflow document (with ``a_galaxy_workflow``, ``format-version``, ``steps``, etc.) nested inside this step. */
  subworkflow: Schema.optional(Schema.Union(NativeGalaxyWorkflowSchema, Schema.Null)),
  /** Embedded tool definition for user-defined (dynamic) tools. Present when the step uses a ``GalaxyUserTool`` instead of a registered tool. Contains the full tool definition including ``class: GalaxyU... */
  tool_representation: Schema.optional(
    Schema.Union(Schema.Record({ key: Schema.String, value: Schema.Unknown }), Schema.Null),
  ),
  /** Default values for step inputs. Keys are parameter names, values are objects with a ``default`` key. */
  in: Schema.optional(
    Schema.Union(Schema.Record({ key: Schema.String, value: Schema.Unknown }), Schema.Null),
  ),
});
export type NativeStep = typeof NativeStepSchema.Type;

export function isNativeCreatorPerson(
  v: NativeCreatorPerson | NativeCreatorOrganization,
): v is NativeCreatorPerson {
  return v?.class === "Person";
}

export function isNativeCreatorOrganization(
  v: NativeCreatorPerson | NativeCreatorOrganization,
): v is NativeCreatorOrganization {
  return v?.class === "Organization";
}

export function isNativeTextComment(
  v: NativeTextComment | NativeMarkdownComment | NativeFrameComment | NativeFreehandComment,
): v is NativeTextComment {
  return v?.type === "text";
}

export function isNativeMarkdownComment(
  v: NativeTextComment | NativeMarkdownComment | NativeFrameComment | NativeFreehandComment,
): v is NativeMarkdownComment {
  return v?.type === "markdown";
}

export function isNativeFrameComment(
  v: NativeTextComment | NativeMarkdownComment | NativeFrameComment | NativeFreehandComment,
): v is NativeFrameComment {
  return v?.type === "frame";
}

export function isNativeFreehandComment(
  v: NativeTextComment | NativeMarkdownComment | NativeFrameComment | NativeFreehandComment,
): v is NativeFreehandComment {
  return v?.type === "freehand";
}
