// AUTO-GENERATED by scripts/bundle-templates.mjs — do not edit.
// This stub is committed so TypeScript compiles without a prior build.
// Running `pnpm build` (or `node scripts/bundle-templates.mjs`) replaces
// the empty map with the actual inlined template strings.
export const BUNDLED_TEMPLATES: Record<string, string> = {};
