// AUTO-GENERATED by scripts/bundle-templates.mjs — do not edit.
export const BUNDLED_TEMPLATES: Record<string, string> = {
  "_macros.md.j2": `{#-
  Shared macros for workflow_state report templates.

  IMPORTANT: every construct used here must also be valid in Nunjucks so
  the TypeScript mirror can render identical markdown. That means: only
  \`for\`, \`if\`, \`set\`, \`macro\`, \`import\`, \`include\`, and the shared-subset
  filters (\`length\`, \`default\`, \`upper\`, \`lower\`, \`replace\`, \`join\`,
  \`sort\`, \`selectattr\`). No custom filters, no globals.
-#}

{#-
  status_badge(label)
  Renders the summary-line badge shared across every report header.
-#}
{% macro status_badge(label) -%}
**Status:** {{ label }}
{%- endmacro %}

{#-
  kv_summary(summary)
  Render a dict-of-counts as \`\`key: value, key: value\`\` (insertion order
  is preserved by Pydantic \`\`model_dump\`\`, so upstream models control
  ordering). Used under the status badge in every report header.
-#}
{% macro kv_summary(summary) -%}
{% for key, value in summary.items() -%}
{{ key }}: {{ value }}{% if not loop.last %}, {% endif %}
{%- endfor %}
{%- endmacro %}

{#-
  workflow_state_cells(r)
  Renders the 5 trailing cells of a workflow table row — handling the
  error / skipped / ok three-branch logic that every current
  \`\`format_*_markdown\`\` reimplements. \`\`r\`\` is the json-dumped
  workflow result dict.

  Expected columns (Total | OK | Fail | Skip | Details). Callers provide
  the leading \`\`| name\`\` cell themselves so they can choose how to label
  it (basename, relative_path, etc.).
-#}
{% macro workflow_state_cells(r) -%}
{% if r.skipped_reason -%}
- | - | - | - | SKIPPED: {{ r.skipped_reason }}
{%- elif r.error -%}
- | - | - | - | ERROR: {{ r.error }}
{%- else -%}
{% set s = r.summary %}
{{ (r.results | length) }} | {{ s.ok }} | {{ s.fail }} | {{ s.skip }} |
{%- endif %}
{%- endmacro %}

{#-
  failure_bullet(f)
  Renders a single \`\`all_failures\`\` entry as a markdown bullet. The input
  dict has keys \`\`workflow\`\`, \`\`step\`\`, \`\`tool_id\`\`, \`\`message\`\`.
-#}
{% macro failure_bullet(f) -%}
- **{{ f.workflow }}** Step {{ f.step }} ({{ f.tool_id }}): {{ f.message }}
{%- endmacro %}
`,
  "clean_tree.md.j2": `{#-
  Tree-level report for \`\`gxwf-state-clean\`\`.

  Three sections: affected-workflows table, clean-workflows banner, and
  per-workflow detail bullets. Uses \`\`selectattr("removed_keys")\`\` and
  \`\`selectattr("total_removed")\`\` for filtering, \`\`loop.first\`\` to gate
  the Per-Workflow Details header, and the \`\`steps_affected\`\` +
  \`\`display_label\`\` computed fields landed in step 1.

  Context:
    report — TreeCleanReport as json-dumped dict (\`\`results\`\` → \`\`workflows\`\`)
    meta   — ignored here; kept for uniform signature
-#}
# Stale State Cleaning Report

Root: \`{{ report.root }}\`
Workflows: {{ report.workflows | length }} | {{ report.summary.total_keys }} stale key(s) across {{ report.summary.affected }} workflow(s)

{% if report.summary.affected > 0 or report.summary.errors > 0 %}
## Affected Workflows

| Workflow | Steps Affected | Keys Removed | Details |
| --- | --- | --- | --- |
{% for r in report.workflows %}
{% if r.error %}
| {{ r.path }} | - | - | ERROR: {{ r.error }} |
{% elif r.total_removed > 0 %}
| {{ r.path }} | {{ r.steps_affected }} | {{ r.total_removed }} | {% for sr in r.results | selectattr("removed_keys") %}Step {{ sr.step }} ({{ sr.tool_id }}): {{ sr.removed_keys | join(", ") }}{% if not loop.last %}; {% endif %}{% endfor %} |
{% endif %}
{% endfor %}

{% endif %}
{% if report.summary.clean > 0 %}
## Clean Workflows ({{ report.summary.clean }})

All other workflows have no stale keys.

{% endif %}
{% for r in report.workflows | selectattr("total_removed") %}
{% if loop.first %}
## Per-Workflow Details

{% endif %}
### {{ r.path }}
{% for sr in r.results | selectattr("removed_keys") %}
- Step {{ sr.step }} ({{ sr.display_label }}): Removed \`{{ sr.removed_keys | join("\`, \`") }}\`
{% endfor %}

{% endfor %}
`,
  "connection_section.md.j2": `{#-
  Connection validation section.

  Ported verbatim from \`\`validate.format_connection_markdown\`\`. Standalone
  renderer today; also an include target for \`\`validate_tree.md.j2\`\` when a
  workflow carries a \`\`connection_report\`\`.

  Context:
    report — ConnectionValidationReport as json-dumped dict
-#}
{% set s = report.summary %}
{% set valid_label = "VALID" if report.valid else "INVALID" %}
## Connection Validation

**Status:** {{ valid_label }}
**Connections:** {{ s.ok | default(0) }} OK, {{ s.invalid | default(0) }} INVALID, {{ s.skip | default(0) }} SKIP
{% if report.has_details %}

| Source | Target | Status | Mapping | Errors |
| --- | --- | --- | --- | --- |
{% for sr in report.step_results %}
{%   for cr in sr.connections %}
{%     set mapping_cell = cr.mapping if cr.mapping else "-" %}
{%     set errors_cell = cr.errors | join("; ") if cr.errors else "-" %}
| {{ cr.source_step }}/{{ cr.source_output }} | {{ cr.target_step }}/{{ cr.target_input }} | {{ cr.status }} | {{ mapping_cell }} | {{ errors_cell }} |
{%   endfor %}
{%   for err in sr.errors %}
{%     set step_label = (sr.step ~ " (" ~ sr.tool_id ~ ")") if sr.tool_id else sr.step %}
| - | {{ step_label }} | error | - | {{ err }} |
{%   endfor %}
{% endfor %}
{% endif %}
`,
  "export_tree.md.j2": `{#-
  Tree-level report for \`\`gxwf-to-format2-stateful\`\`.

  Pure port of \`\`export_format2._format_tree_markdown\`\`. Content improvements
  (category grouping, per-tool fallback aggregation, skipped appendix) are
  deferred to follow-up commits — per the plan, per-tool fallback aggregation
  needs step-level \`\`tool_id\`\` plumbing that is out of scope here.

  Context:
    report — ExportTreeReport as json-dumped dict (\`\`results\`\` → \`\`workflows\`\`)
    meta   — ignored here; kept for uniform signature
-#}
# Export Report: {{ report.root }}

{% for r in report.workflows %}
{% if r.error %}
- **{{ r.path }}**: ERROR ({{ r.error }})
{% elif r.skipped_reason %}
- **{{ r.path }}**: SKIPPED ({{ r.skipped_reason }})
{% elif r.ok %}
- **{{ r.path }}**: OK ({{ r.steps_converted }} steps)
{% else %}
- **{{ r.path }}**: PARTIAL ({{ r.steps_fallback }} fallbacks)
{% endif %}
{% endfor %}

**Summary**: {{ report.summary.ok }} OK, {{ report.summary.fail }} errors, {{ report.summary.skipped }} skipped
`,
  "lint_tree.md.j2": `{#-
  Tree-level report for \`\`gxwf-lint-stateful\`\`.

  Pure port of \`\`lint_stateful._format_lint_tree_markdown\`\` — single wide
  table with one row per workflow. Uses the \`\`step_counts\`\` computed field
  on \`\`LintWorkflowResult\`\` instead of re-looping \`\`results\`\`.

  Content improvements deferred — surfacing lint messages and exit-code
  meaning needs model + pipeline changes called out in the plan's
  Step 1 "out of scope" list.

  Context:
    report — LintTreeReport as json-dumped dict (\`\`results\`\` → \`\`workflows\`\`)
    meta   — ignored here; kept for uniform signature
-#}
# Lint Report

Root: \`{{ report.root }}\`
Workflows: {{ report.workflows | length }} | Lint: {{ report.summary.lint_errors }} errors, {{ report.summary.lint_warnings }} warnings | State: {{ report.summary.state_ok }} OK, {{ report.summary.state_fail }} FAIL, {{ report.summary.state_skip }} SKIP

| Workflow | Lint Errors | Lint Warnings | State OK | State Fail | State Skip |
| --- | --- | --- | --- | --- | --- |
{% for r in report.workflows %}
{% if r.error %}
| {{ r.path }} | - | - | - | - | ERROR: {{ r.error }} |
{% elif r.skipped_reason %}
| {{ r.path }} | - | - | - | - | SKIPPED |
{% else %}
| {{ r.path }} | {{ r.lint_errors }} | {{ r.lint_warnings }} | {{ r.step_counts.ok }} | {{ r.step_counts.fail }} | {{ r.step_counts.skip }} |
{% endif %}
{% endfor %}
`,
  "roundtrip_tree.md.j2": `{#-
  Tree-level report for \`\`gxwf-roundtrip-validate-tree\`\`.

  Pure port of \`\`roundtrip.format_roundtrip_markdown\`\`. Flat bullet list
  per workflow with sub-bullets for conversion failures and error diffs.

  Context:
    report — RoundTripTreeReport as json-dumped dict (\`\`results\`\` → \`\`workflows\`\`)
    meta   — ignored here; kept for uniform signature
-#}
{% set s = report.summary %}
# Roundtrip Validation: {{ report.root }}

**{{ report.total }} workflows:** {{ s.clean }} clean, {{ s.benign_only }} benign, {{ s.fail }} fail, {{ s.error }} error, {{ s.skipped }} skipped

{% for r in report.workflows %}
{% set benign = r.benign_diffs | length %}
{% set error_count = r.error_diffs | length %}
{% set detail = "" %}
{% if benign %}{% set detail = detail ~ " (" ~ benign ~ " benign)" %}{% endif %}
{% if error_count %}{% set detail = detail ~ " (" ~ error_count ~ " errors)" %}{% endif %}
- **{{ r.workflow_path }}**: {{ r.status | upper }}{{ detail }}
{% for line in r.conversion_failure_lines %}
  - {{ line }}
{% endfor %}
{% for d in r.error_diffs %}
  - {{ d.step_path }}: {{ d.description }}
{% endfor %}
{% endfor %}
`,
  "to_native_tree.md.j2": `{#-
  Tree-level report for \`\`gxwf-to-native-stateful\`\`.

  Pure port of \`\`to_native_stateful._format_tree_markdown\`\`. Structure is
  identical to \`\`export_tree.md.j2\`\` — same four branches, only the H1 and
  the OK-branch count field (\`\`steps_encoded\`\` vs \`\`steps_converted\`\`)
  differ. Content improvements deferred, same rationale as export.

  Context:
    report — ToNativeTreeReport as json-dumped dict (\`\`results\`\` → \`\`workflows\`\`)
    meta   — ignored here; kept for uniform signature
-#}
# Conversion Report: {{ report.root }}

{% for r in report.workflows %}
{% if r.error %}
- **{{ r.path }}**: ERROR ({{ r.error }})
{% elif r.skipped_reason %}
- **{{ r.path }}**: SKIPPED ({{ r.skipped_reason }})
{% elif r.ok %}
- **{{ r.path }}**: OK ({{ r.steps_encoded }} steps)
{% else %}
- **{{ r.path }}**: PARTIAL ({{ r.steps_fallback }} fallbacks)
{% endif %}
{% endfor %}

**Summary**: {{ report.summary.ok }} OK, {{ report.summary.fail }} errors, {{ report.summary.skipped }} skipped
`,
  "validate_tree.md.j2": `{#-
  Tree-level report for \`\`gxwf-state-validate\`\`.

  Pure port of \`\`validate.format_tree_markdown\`\`. Per-category tables with
  a Details column showing failure counts, a Failure Details appendix using
  \`\`report.all_failures\`\`, and per-workflow connection sections via
  \`\`{% include "connection_section.md.j2" %}\`\`.

  The \`\`workflow_state_cells\`\` macro is NOT used here because the validate
  table has a 6th "Details" column whose content varies (failure count for
  normal rows, SKIPPED/ERROR for exceptional rows) — inlining the 3-branch
  logic keeps the template straightforward.

  Context:
    report — TreeValidationReport as json-dumped dict (\`\`results\`\` → \`\`workflows\`\`)
    meta   — ignored here; kept for uniform signature
-#}
{% import "_macros.md.j2" as m %}
{% set s = report.summary %}
# Workflow Validation Report

Root: \`{{ report.root }}\`
Workflows: {{ report.workflows | length }} | Steps: {{ s.ok }} OK, {{ s.fail }} FAIL, {{ s.skip }} SKIP, {{ s.error }} ERROR{% if s.skipped %} | {{ s.skipped }} workflow(s) skipped{% endif %}


{% for cat in report.categories %}
## {{ cat.name }} ({{ cat.results | length }} workflows)

| Workflow | Steps | OK | Fail | Skip | Details |
| --- | --- | --- | --- | --- | --- |
{% for r in cat.results %}
{% if r.skipped_reason %}
| {{ r.name }} | - | - | - | - | SKIPPED: {{ r.skipped_reason }} |
{% elif r.error %}
| {{ r.name }} | - | - | - | - | ERROR: {{ r.error }} |
{% else %}
{% set fail_count = r.failures | length %}
| {{ r.name }} | {{ r.results | length }} | {{ r.summary.ok }} | {{ r.summary.fail }} | {{ r.summary.skip }} | {% if fail_count %}{{ fail_count }} failure(s){% endif %} |
{% endif %}
{% endfor %}

{% endfor %}
{% if report.all_failures %}
## Failure Details

{% for f in report.all_failures %}
{{ m.failure_bullet(f) }}
{% endfor %}

{% endif %}
{% for r in report.workflows | selectattr("connection_report") %}
## Connections: {{ r.path }}

{% set report = r.connection_report %}
{% include "connection_section.md.j2" %}

{% endfor %}
`,
};
